/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Du_An_DESIGN;

import Du_An_HELPER.ThongBao;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author LENOVO
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/Du_An_IMAGES/produc.png"));
        Image image = icon.getImage();
        setIconImage(image);
        this.setSize(1400, 850);
        lblTenDN.setText(frmLogin.nv.getTenNV());

        new Thread() {

            public void run() {
                while (true) {
                    Calendar ca = new GregorianCalendar();
                    int Hour = ca.get(Calendar.HOUR);
                    int minute = ca.get(Calendar.MINUTE);
                    int Second = ca.get(Calendar.SECOND);
                    int PM_AM = ca.get(Calendar.AM_PM);
                    String day_night;

                    if (PM_AM == 1) {
                        day_night = "PM";
                    } else {
                        day_night = "AM";
                    }
                    String time = "TIME: " + Hour + ":" + minute + ":" + Second + " " + day_night;
                    lblThoiGian.setText(time);

                    //4565gyhfd
                }

            }

        }.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnNhanVien = new javax.swing.JButton();
        btnSanPham = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnXuatHang = new javax.swing.JButton();
        btnNhapHang = new javax.swing.JButton();
        btnNhaCungCap = new javax.swing.JButton();
        btnCTBH = new javax.swing.JButton();
        btnCTBH1 = new javax.swing.JButton();
        lblThoiGian = new javax.swing.JLabel();
        lblTenDN = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tabChuongTrinh = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(203, 224, 255));

        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);
        jToolBar1.setOpaque(false);

        btnNhanVien.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnNhanVien.setForeground(new java.awt.Color(0, 0, 204));
        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/nhanvien.png"))); // NOI18N
        btnNhanVien.setText("Nhân Viên");
        btnNhanVien.setFocusable(false);
        btnNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNhanVien.setIconTextGap(20);
        btnNhanVien.setMargin(new java.awt.Insets(5, 15, 5, 15));
        btnNhanVien.setMaximumSize(new java.awt.Dimension(160, 60));
        btnNhanVien.setMinimumSize(new java.awt.Dimension(160, 60));
        btnNhanVien.setOpaque(false);
        btnNhanVien.setVerifyInputWhenFocusTarget(false);
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNhanVien);

        btnSanPham.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnSanPham.setForeground(new java.awt.Color(0, 0, 153));
        btnSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/sanpham.png"))); // NOI18N
        btnSanPham.setText("Sản Phẩm");
        btnSanPham.setFocusable(false);
        btnSanPham.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSanPham.setIconTextGap(20);
        btnSanPham.setMargin(new java.awt.Insets(5, 15, 5, 15));
        btnSanPham.setMaximumSize(new java.awt.Dimension(160, 60));
        btnSanPham.setMinimumSize(new java.awt.Dimension(160, 60));
        btnSanPham.setOpaque(false);
        btnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSanPham);

        btnKhachHang.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnKhachHang.setForeground(new java.awt.Color(0, 0, 153));
        btnKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/khachang.png"))); // NOI18N
        btnKhachHang.setText("Khách Hàng");
        btnKhachHang.setFocusable(false);
        btnKhachHang.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnKhachHang.setIconTextGap(10);
        btnKhachHang.setMargin(new java.awt.Insets(5, 15, 5, 15));
        btnKhachHang.setMaximumSize(new java.awt.Dimension(160, 60));
        btnKhachHang.setMinimumSize(new java.awt.Dimension(160, 60));
        btnKhachHang.setOpaque(false);
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKhachHang);

        btnXuatHang.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnXuatHang.setForeground(new java.awt.Color(0, 0, 153));
        btnXuatHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/QLHD.png"))); // NOI18N
        btnXuatHang.setText("Xuất Hàng");
        btnXuatHang.setFocusable(false);
        btnXuatHang.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnXuatHang.setIconTextGap(20);
        btnXuatHang.setMargin(new java.awt.Insets(5, 15, 5, 15));
        btnXuatHang.setMaximumSize(new java.awt.Dimension(160, 60));
        btnXuatHang.setMinimumSize(new java.awt.Dimension(160, 60));
        btnXuatHang.setOpaque(false);
        btnXuatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatHangActionPerformed(evt);
            }
        });
        jToolBar1.add(btnXuatHang);

        btnNhapHang.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnNhapHang.setForeground(new java.awt.Color(0, 0, 153));
        btnNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/QLHD.png"))); // NOI18N
        btnNhapHang.setText("Nhập Hàng");
        btnNhapHang.setFocusable(false);
        btnNhapHang.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNhapHang.setIconTextGap(15);
        btnNhapHang.setMargin(new java.awt.Insets(5, 15, 5, 15));
        btnNhapHang.setMaximumSize(new java.awt.Dimension(160, 60));
        btnNhapHang.setMinimumSize(new java.awt.Dimension(160, 60));
        btnNhapHang.setOpaque(false);
        btnNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapHangActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNhapHang);

        btnNhaCungCap.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnNhaCungCap.setForeground(new java.awt.Color(0, 0, 153));
        btnNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/NCC.png"))); // NOI18N
        btnNhaCungCap.setText("Nhà CC");
        btnNhaCungCap.setFocusable(false);
        btnNhaCungCap.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNhaCungCap.setIconTextGap(30);
        btnNhaCungCap.setMargin(new java.awt.Insets(5, 15, 5, 15));
        btnNhaCungCap.setMaximumSize(new java.awt.Dimension(160, 60));
        btnNhaCungCap.setMinimumSize(new java.awt.Dimension(160, 60));
        btnNhaCungCap.setName(""); // NOI18N
        btnNhaCungCap.setOpaque(false);
        btnNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhaCungCapActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNhaCungCap);

        btnCTBH.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnCTBH.setForeground(new java.awt.Color(0, 0, 153));
        btnCTBH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/BH.png"))); // NOI18N
        btnCTBH.setText("Bảo Hành");
        btnCTBH.setFocusable(false);
        btnCTBH.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCTBH.setIconTextGap(20);
        btnCTBH.setMargin(new java.awt.Insets(5, 15, 5, 15));
        btnCTBH.setMaximumSize(new java.awt.Dimension(160, 60));
        btnCTBH.setMinimumSize(new java.awt.Dimension(160, 60));
        btnCTBH.setOpaque(false);
        btnCTBH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCTBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTBHActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCTBH);

        btnCTBH1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnCTBH1.setForeground(new java.awt.Color(0, 0, 153));
        btnCTBH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/BH.png"))); // NOI18N
        btnCTBH1.setText("Đăng Xuất");
        btnCTBH1.setFocusable(false);
        btnCTBH1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCTBH1.setIconTextGap(20);
        btnCTBH1.setMargin(new java.awt.Insets(5, 15, 5, 15));
        btnCTBH1.setMaximumSize(new java.awt.Dimension(160, 60));
        btnCTBH1.setMinimumSize(new java.awt.Dimension(160, 60));
        btnCTBH1.setOpaque(false);
        btnCTBH1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCTBH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTBH1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCTBH1);

        lblThoiGian.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblThoiGian.setForeground(new java.awt.Color(255, 0, 0));
        lblThoiGian.setText("TIME:");
        jToolBar1.add(lblThoiGian);

        lblTenDN.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTenDN.setForeground(new java.awt.Color(255, 0, 51));
        lblTenDN.setText("Ten dang nhap");
        lblTenDN.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jToolBar1.add(lblTenDN);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Phần Mềm Quản Lý Kho ");
        jToolBar1.add(jLabel3);

        tabChuongTrinh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jPanel1.setOpaque(false);

        kGradientPanel2.setkEndColor(new java.awt.Color(203, 224, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setOpaque(false);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/13.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Copyright © 2020 Executing. All rights reserved.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );

        tabChuongTrinh.addTab(" Introduce", jPanel1);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabChuongTrinh))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabChuongTrinh)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1191, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here:
        
        if (!frmLogin.nv.getChucVu().trim().equals("GD")) {
            ThongBao.ThongBaoSQL("Thông Báo", "Bạn Không có quyền truy Cập Chức Năng này!!!");
            return;
        }
        int index1 = tabChuongTrinh.indexOfTab("Quản Lý Nhân Viên");
        if (index1 > 0) {
            tabChuongTrinh.remove(index1);
        } else {

            TabNhanVien pnl1 = new TabNhanVien();

            tabChuongTrinh.add(pnl1, "Quản Lý Nhân Viên");

            int index = tabChuongTrinh.indexOfTab("Quản Lý Nhân Viên");
            tabChuongTrinh.setSelectedIndex(index);
            JPanel pnlTab = new JPanel(new GridBagLayout());
            pnlTab.setOpaque(false);
            JLabel lblTitle = new JLabel("Quản Lý Nhân Viên");

            JButton btnClose = new JButton("x");

            GridBagConstraints gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 0;
            gbc.weightx = 1;

            pnlTab.add(lblTitle, gbc);

            gbc.gridx++;
            gbc.weightx = 0;
            pnlTab.add(btnClose, gbc);

            tabChuongTrinh.setTabComponentAt(index, pnlTab);
            btnClose.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    int index1 = tabChuongTrinh.indexOfTab("Quản Lý Nhân Viên");
                    tabChuongTrinh.remove(index1);
                }
            });

            tabChuongTrinh.setSelectedIndex(index);
        }
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        // TODO add your handling code here:
        int index1 = tabChuongTrinh.indexOfTab("Quản Lý Sản Phẩm");
        if (index1 > 0) {
            tabChuongTrinh.remove(index1);
        } else {

            TabSanPham pnl1 = new TabSanPham();

            tabChuongTrinh.add(pnl1, "Quản Lý Sản Phẩm");

            int index = tabChuongTrinh.indexOfTab("Quản Lý Sản Phẩm");
            tabChuongTrinh.setSelectedIndex(index);
            JPanel pnlTab = new JPanel(new GridBagLayout());
            pnlTab.setOpaque(false);
            JLabel lblTitle = new JLabel("Quản Lý Sản Phẩm");

            JButton btnClose = new JButton("x");

            GridBagConstraints gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 0;
            gbc.weightx = 1;

            pnlTab.add(lblTitle, gbc);

            gbc.gridx++;
            gbc.weightx = 0;
            pnlTab.add(btnClose, gbc);

            tabChuongTrinh.setTabComponentAt(index, pnlTab);
            btnClose.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    int index1 = tabChuongTrinh.indexOfTab("Quản Lý Sản Phẩm");
                    tabChuongTrinh.remove(index1);
                }
            });

            tabChuongTrinh.setSelectedIndex(index);
        }
    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        // TODO add your handling code here:
        int index1 = tabChuongTrinh.indexOfTab("Quản Lý Khách Hàng");
        if (index1 > 0) {
            tabChuongTrinh.remove(index1);
        } else {

            TabKhachHang pnl1 = new TabKhachHang();

            tabChuongTrinh.add(pnl1, "Quản Lý Khách Hàng");

            int index = tabChuongTrinh.indexOfTab("Quản Lý Khách Hàng");
            tabChuongTrinh.setSelectedIndex(index);
            JPanel pnlTab = new JPanel(new GridBagLayout());
            pnlTab.setOpaque(false);
            JLabel lblTitle = new JLabel("Quản Lý Khách Hàng");

            JButton btnClose = new JButton("x");

            GridBagConstraints gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 0;
            gbc.weightx = 1;

            pnlTab.add(lblTitle, gbc);

            gbc.gridx++;
            gbc.weightx = 0;
            pnlTab.add(btnClose, gbc);

            tabChuongTrinh.setTabComponentAt(index, pnlTab);
            btnClose.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    int index1 = tabChuongTrinh.indexOfTab("Quản Lý Khách Hàng");
                    tabChuongTrinh.remove(index1);
                }
            });

            tabChuongTrinh.setSelectedIndex(index);
        }
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhaCungCapActionPerformed
        // TODO add your handling code here:
        int index1 = tabChuongTrinh.indexOfTab("Quản Lý Nhà Cung Cấp");
        if (index1 > 0) {
            tabChuongTrinh.remove(index1);
        } else {

            TabNhaCungCap pnl1 = new TabNhaCungCap();

            tabChuongTrinh.add(pnl1, "Quản Lý Nhà Cung Cấp");

            int index = tabChuongTrinh.indexOfTab("Quản Lý Nhà Cung Cấp");
            tabChuongTrinh.setSelectedIndex(index);
            JPanel pnlTab = new JPanel(new GridBagLayout());
            pnlTab.setOpaque(false);
            JLabel lblTitle = new JLabel("Quản Lý Nhà Cung Cấp");

            JButton btnClose = new JButton("x");

            GridBagConstraints gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 0;
            gbc.weightx = 1;

            pnlTab.add(lblTitle, gbc);

            gbc.gridx++;
            gbc.weightx = 0;
            pnlTab.add(btnClose, gbc);

            tabChuongTrinh.setTabComponentAt(index, pnlTab);
            btnClose.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    int index1 = tabChuongTrinh.indexOfTab("Quản Lý Nhà Cung Cấp");
                    tabChuongTrinh.remove(index1);
                }
            });

            tabChuongTrinh.setSelectedIndex(index);
        }
    }//GEN-LAST:event_btnNhaCungCapActionPerformed

    private void btnXuatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatHangActionPerformed
        // TODO add your handling code here:
        int index1 = tabChuongTrinh.indexOfTab("Quản Lý Hoá Đơn Xuất");
        if (index1 > 0) {
            tabChuongTrinh.remove(index1);
        } else {

            TabHD_Xuat pnl1 = new TabHD_Xuat();

            tabChuongTrinh.add(pnl1, "Quản Lý Hoá Đơn Xuất");

            int index = tabChuongTrinh.indexOfTab("Quản Lý Hoá Đơn Xuất");
            tabChuongTrinh.setSelectedIndex(index);
            JPanel pnlTab = new JPanel(new GridBagLayout());
            pnlTab.setOpaque(false);
            JLabel lblTitle = new JLabel("Quản Lý Hoá Đơn Xuất");

            JButton btnClose = new JButton("x");

            GridBagConstraints gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 0;
            gbc.weightx = 1;

            pnlTab.add(lblTitle, gbc);

            gbc.gridx++;
            gbc.weightx = 0;
            pnlTab.add(btnClose, gbc);

            tabChuongTrinh.setTabComponentAt(index, pnlTab);
            btnClose.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    int index1 = tabChuongTrinh.indexOfTab("Quản Lý Hoá Đơn Xuất");
                    tabChuongTrinh.remove(index1);
                }
            });

            tabChuongTrinh.setSelectedIndex(index);
        }

    }//GEN-LAST:event_btnXuatHangActionPerformed

    private void btnNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapHangActionPerformed
        // TODO add your handling code here:
        int index1 = tabChuongTrinh.indexOfTab("Quản Lý Hoá Đơn Nhập");
        if (index1 > 0) {
            tabChuongTrinh.remove(index1);
        } else {

            TabHD_Nhap pnl1 = new TabHD_Nhap();

            tabChuongTrinh.add(pnl1, "Quản Lý Hoá Đơn Nhập");

            int index = tabChuongTrinh.indexOfTab("Quản Lý Hoá Đơn Nhập");
            tabChuongTrinh.setSelectedIndex(index);
            JPanel pnlTab = new JPanel(new GridBagLayout());
            pnlTab.setOpaque(false);
            JLabel lblTitle = new JLabel("Quản Lý Hoá Đơn Nhập");

            JButton btnClose = new JButton("x");

            GridBagConstraints gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 0;
            gbc.weightx = 1;

            pnlTab.add(lblTitle, gbc);

            gbc.gridx++;
            gbc.weightx = 0;
            pnlTab.add(btnClose, gbc);

            tabChuongTrinh.setTabComponentAt(index, pnlTab);
            btnClose.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    int index1 = tabChuongTrinh.indexOfTab("Quản Lý Hoá Đơn Nhập");
                    tabChuongTrinh.remove(index1);
                }
            });

            tabChuongTrinh.setSelectedIndex(index);
        }
    }//GEN-LAST:event_btnNhapHangActionPerformed

    private void btnCTBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTBHActionPerformed
        // TODO add your handling code here:
        int index1 = tabChuongTrinh.indexOfTab("Phiếu CTBH");
        if (index1 > 0) {
            tabChuongTrinh.remove(index1);
        } else {

            TabCTBH pnl1 = new TabCTBH();

            tabChuongTrinh.add(pnl1, "Phiếu CTBH");

            int index = tabChuongTrinh.indexOfTab("Phiếu CTBH");
            tabChuongTrinh.setSelectedIndex(index);
            JPanel pnlTab = new JPanel(new GridBagLayout());
            pnlTab.setOpaque(false);
            JLabel lblTitle = new JLabel("Phiếu CTBH");

            JButton btnClose = new JButton("x");

            GridBagConstraints gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 0;
            gbc.weightx = 1;

            pnlTab.add(lblTitle, gbc);

            gbc.gridx++;
            gbc.weightx = 0;
            pnlTab.add(btnClose, gbc);

            tabChuongTrinh.setTabComponentAt(index, pnlTab);
            btnClose.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    int index1 = tabChuongTrinh.indexOfTab("Phiếu CTBH");
                    tabChuongTrinh.remove(index1);
                }
            });

            tabChuongTrinh.setSelectedIndex(index);
        }
    }//GEN-LAST:event_btnCTBHActionPerformed

    private void btnCTBH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTBH1ActionPerformed
        // TODO add your handling code here:
        int rs = JOptionPane.showConfirmDialog(this, "Bạn muốn thoát không",
                "Xác nhận thoát", JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if (rs == JOptionPane.YES_OPTION) {
           frmLogin lg = new frmLogin();
           lg.setVisible(true);
           this.dispose();
        }
    }//GEN-LAST:event_btnCTBH1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCTBH;
    private javax.swing.JButton btnCTBH1;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnNhaCungCap;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnNhapHang;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JButton btnXuatHang;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lblTenDN;
    private javax.swing.JLabel lblThoiGian;
    private javax.swing.JTabbedPane tabChuongTrinh;
    // End of variables declaration//GEN-END:variables
}
