/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Du_An_DESIGN;

//import ASM_TT_BLL.BLLHangSX;
//import ASM_TT_BLL.BLLLoaiSP;
//import ASM_TT_BLL.BLLSanPham;
//import ASM_TT_DTO.HangSX;
//import ASM_TT_DTO.LoaiSP;
//import ASM_TT_HALPER.ThongBao;
import Du_An_BLL.BLLHangSX;
import Du_An_DTO.HangSX;
import Du_An_HELPER.ThongBao;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author LENOVO
 */
public class jdlHangSX extends javax.swing.JDialog {
    
    /**
     * Creates new form jdlLoaiSanPham
     */
    public jdlHangSX(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        txtMoTa.setBackground(new Color(0, 0, 0, 0));
        //txtMaLoai.setBackground(new Color(0, 0, 0, 0));
        txtTenHang.setBackground(new Color(0, 0, 0, 0));
        txtMaHangSanXuat.setText(BLLHangSX.TaoMaHSX());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHoTen1 = new javax.swing.JLabel();
        lblHoTen2 = new javax.swing.JLabel();
        lblHoTen3 = new javax.swing.JLabel();
        txtMoTa = new com.shady.scontrols.STextField();
        SbtnThem = new com.shady.scontrols.SButton();
        SbtnHuy = new com.shady.scontrols.SButton();
        txtMaHangSanXuat = new com.shady.scontrols.STextField();
        txtTenHang = new com.shady.scontrols.STextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(203, 224, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hãng Sản Xuẩt", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(51, 0, 255))); // NOI18N

        lblHoTen1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblHoTen1.setForeground(new java.awt.Color(0, 0, 153));
        lblHoTen1.setText("Tên Hãng SX");

        lblHoTen2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblHoTen2.setForeground(new java.awt.Color(0, 0, 153));
        lblHoTen2.setText("Mô Tả");

        lblHoTen3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblHoTen3.setForeground(new java.awt.Color(0, 0, 153));
        lblHoTen3.setText("Mã Hãng Sản Xuất");

        txtMoTa.setForeground(new java.awt.Color(0, 0, 204));
        txtMoTa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMoTa.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtMoTa.sets_placeholder("Mời Bạn Nhập");
        txtMoTa.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtMoTa.sets_placeholderForeGround(new java.awt.Color(153, 0, 204));

        SbtnThem.setText("Thêm");
        SbtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnThemActionPerformed(evt);
            }
        });

        SbtnHuy.setText("Huỷ");
        SbtnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnHuyActionPerformed(evt);
            }
        });

        txtMaHangSanXuat.setEditable(false);
        txtMaHangSanXuat.setForeground(new java.awt.Color(0, 0, 204));
        txtMaHangSanXuat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMaHangSanXuat.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtMaHangSanXuat.sets_placeholder("Mời Bạn Nhập");
        txtMaHangSanXuat.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtMaHangSanXuat.sets_placeholderForeGround(new java.awt.Color(153, 0, 204));

        txtTenHang.setForeground(new java.awt.Color(0, 0, 204));
        txtTenHang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTenHang.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtTenHang.sets_placeholder("Mời Bạn Nhập");
        txtTenHang.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtTenHang.sets_placeholderForeGround(new java.awt.Color(153, 0, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHoTen3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoTen1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoTen2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SbtnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SbtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTenHang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMaHangSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoTen3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaHangSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoTen1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoTen2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SbtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SbtnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SbtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnThemActionPerformed
        // TODO add your handling code here:
        
        String MaHSX = txtMaHangSanXuat.getText();
              String TenLoaiSP = txtTenHang.getText();
        String MoTa = txtMoTa.getText();
       if (this.txtTenHang.getText().length() == 0) {
           ThongBao.ThongBaoSQL("Thông Báo", "Tên Hãng SX Không Được Bỏ Trống");
        } else {
          HangSX hsx = new HangSX(MaHSX, TenLoaiSP, MoTa);
          BLLHangSX.ThemHangSX(hsx);
          ThongBao.ThongBaoSQL("Thông Báo", "Thêm thành công");
          
        }
    }//GEN-LAST:event_SbtnThemActionPerformed

    private void SbtnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnHuyActionPerformed
        // TODO add your handling code here:
           this.dispose();
    }//GEN-LAST:event_SbtnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdlHangSX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdlHangSX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdlHangSX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdlHangSX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdlHangSX dialog = new jdlHangSX(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.shady.scontrols.SButton SbtnHuy;
    private com.shady.scontrols.SButton SbtnThem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHoTen1;
    private javax.swing.JLabel lblHoTen2;
    private javax.swing.JLabel lblHoTen3;
    private com.shady.scontrols.STextField txtMaHangSanXuat;
    private com.shady.scontrols.STextField txtMoTa;
    private com.shady.scontrols.STextField txtTenHang;
    // End of variables declaration//GEN-END:variables
}
