/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Du_An_DESIGN;

import Du_An_BLL.BLLHangSX;
import Du_An_BLL.BLLLoaiSP;
import Du_An_DAL.DALLoaiSP;
import Du_An_DTO.HangSX;
import Du_An_DTO.LoaiSP;
import Du_An_HELPER.ThongBao;

/**
 *
 * @author LENOVO
 */
public class jdlLoaiSanPham extends javax.swing.JDialog {

    /**
     * Creates new form jdlLoaiSanPham
     */
    public jdlLoaiSanPham(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtHMaLoaiSanPham.setText(BLLLoaiSP.TaoMaLSP());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHoTen1 = new javax.swing.JLabel();
        lblHoTen2 = new javax.swing.JLabel();
        lblHoTen3 = new javax.swing.JLabel();
        txtMota = new com.shady.scontrols.STextField();
        SbtnThem = new com.shady.scontrols.SButton();
        SbtnHuy = new com.shady.scontrols.SButton();
        txtHMaLoaiSanPham = new com.shady.scontrols.STextField();
        txtTenLoaiSanPham = new com.shady.scontrols.STextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(203, 224, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Loại Sản Phẩm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(51, 0, 255))); // NOI18N

        lblHoTen1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblHoTen1.setForeground(new java.awt.Color(0, 0, 153));
        lblHoTen1.setText("Tên Loại Sản Phẩm");

        lblHoTen2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblHoTen2.setForeground(new java.awt.Color(0, 0, 153));
        lblHoTen2.setText("Mô Tả");

        lblHoTen3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblHoTen3.setForeground(new java.awt.Color(0, 0, 153));
        lblHoTen3.setText("Mã Loại Sản Phẩm");

        txtMota.setBackground(new java.awt.Color(203, 224, 255));
        txtMota.setForeground(new java.awt.Color(0, 0, 204));
        txtMota.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMota.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtMota.sets_placeholder("Mời Bạn Nhập");
        txtMota.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtMota.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));

        SbtnThem.setText("Thêm");
        SbtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnThemActionPerformed(evt);
            }
        });

        SbtnHuy.setText("Huỷ");
        SbtnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnHuyActionPerformed(evt);
            }
        });

        txtHMaLoaiSanPham.setEditable(false);
        txtHMaLoaiSanPham.setBackground(new java.awt.Color(203, 224, 255));
        txtHMaLoaiSanPham.setForeground(new java.awt.Color(0, 0, 204));
        txtHMaLoaiSanPham.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtHMaLoaiSanPham.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtHMaLoaiSanPham.sets_placeholder("Mời Bạn Nhập");
        txtHMaLoaiSanPham.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtHMaLoaiSanPham.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));

        txtTenLoaiSanPham.setBackground(new java.awt.Color(203, 224, 255));
        txtTenLoaiSanPham.setForeground(new java.awt.Color(0, 0, 204));
        txtTenLoaiSanPham.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTenLoaiSanPham.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtTenLoaiSanPham.sets_placeholder("Mời Bạn Nhập");
        txtTenLoaiSanPham.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtTenLoaiSanPham.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHoTen3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoTen1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoTen2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SbtnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SbtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTenLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHMaLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMota, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoTen3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHMaLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoTen1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoTen2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SbtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SbtnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SbtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnThemActionPerformed
        // TODO add your handling code here:
        String MaLSP = txtHMaLoaiSanPham.getText();
               String TenLoaiSP = txtTenLoaiSanPham.getText();
               String MoTa = txtMota.getText();
               if (this.txtTenLoaiSanPham.getText().length() == 0) {
                       ThongBao.ThongBaoSQL("Thông Báo", "Tên Hãng SX Không Được Bỏ Trống");
                    } else {
                       LoaiSP lsp = new LoaiSP(MaLSP, TenLoaiSP, MoTa);
                       DALLoaiSP.ThemLoaiSP(lsp);
                       ThongBao.ThongBaoSQL("Thông Báo", "Thêm thành công");
            
                    }
    }//GEN-LAST:event_SbtnThemActionPerformed

    private void SbtnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnHuyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_SbtnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdlLoaiSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdlLoaiSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdlLoaiSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdlLoaiSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdlLoaiSanPham dialog = new jdlLoaiSanPham(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.shady.scontrols.SButton SbtnHuy;
    private com.shady.scontrols.SButton SbtnThem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHoTen1;
    private javax.swing.JLabel lblHoTen2;
    private javax.swing.JLabel lblHoTen3;
    private com.shady.scontrols.STextField txtHMaLoaiSanPham;
    private com.shady.scontrols.STextField txtMota;
    private com.shady.scontrols.STextField txtTenLoaiSanPham;
    // End of variables declaration//GEN-END:variables
}
