/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Du_An_DESIGN;

import Du_An_BLL.BLLBaoHanh;
import Du_An_DTO.PhieuTNBH;
import java.util.Date;

/**
 *
 * @author LENOVO
 */
public class TabBaoHanh extends javax.swing.JPanel {

    /**
     * Creates new form TabBaoHanh
     */
    public TabBaoHanh() {
        initComponents();
        //BLLBaoHanh.LoadKhachHang(tblBH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel4 = new javax.swing.JPanel();
        lblMaPhieuBaoHanh = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        cbbKhachHang = new javax.swing.JComboBox<>();
        sButton1 = new com.shady.scontrols.SButton();
        txtMa = new com.shady.scontrols.STextField();
        txtMaNV = new com.shady.scontrols.STextField();
        lblTenKhoHang = new javax.swing.JLabel();
        sTextField2 = new com.shady.scontrols.STextField();
        lblMaKH = new javax.swing.JLabel();
        txtGhiChu = new com.shady.scontrols.STextField();
        lblMaNV = new javax.swing.JLabel();
        sTextField4 = new com.shady.scontrols.STextField();
        lblDiaChi = new javax.swing.JLabel();
        lblNgayMua = new javax.swing.JLabel();
        txtNHenTra = new com.toedter.calendar.JDateChooser();
        lblMaHDXuat = new javax.swing.JLabel();
        sTextField5 = new com.shady.scontrols.STextField();

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkGradientFocus(600);
        kGradientPanel1.setkStartColor(new java.awt.Color(203, 224, 255));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phiếu Bảo Hành", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel4.setOpaque(false);

        lblMaPhieuBaoHanh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMaPhieuBaoHanh.setText("MaNV");

        lblSDT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSDT.setText("SĐT Kho Hàng");

        cbbKhachHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbKhachHang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbKhachHangItemStateChanged(evt);
            }
        });

        sButton1.setForeground(new java.awt.Color(0, 0, 204));
        sButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/nhapmoi.png"))); // NOI18N
        sButton1.setText("Xuất Phiếu ");
        sButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        sButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButton1ActionPerformed(evt);
            }
        });

        txtMa.setForeground(new java.awt.Color(0, 0, 153));
        txtMa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMa.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtMa.sets_placeholder("............");
        txtMa.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtMa.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));

        txtMaNV.setForeground(new java.awt.Color(0, 0, 204));
        txtMaNV.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMaNV.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtMaNV.sets_placeholder("Mời Bạn Nhập");
        txtMaNV.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtMaNV.sets_placeholderForeGround(new java.awt.Color(204, 0, 204));

        lblTenKhoHang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTenKhoHang.setText("Tên Kho Hàng");

        sTextField2.setForeground(new java.awt.Color(0, 0, 153));
        sTextField2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        sTextField2.sets_BgColor(new java.awt.Color(203, 224, 255));
        sTextField2.sets_placeholder("Mời Bạn Nhập");
        sTextField2.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        sTextField2.sets_placeholderForeGround(new java.awt.Color(204, 0, 204));

        lblMaKH.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMaKH.setText("Mã Khách Hàng");

        txtGhiChu.setForeground(new java.awt.Color(0, 0, 153));
        txtGhiChu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtGhiChu.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtGhiChu.sets_placeholder("Mời Bạn Nhập");
        txtGhiChu.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtGhiChu.sets_placeholderForeGround(new java.awt.Color(204, 0, 204));

        lblMaNV.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMaNV.setText("Mã Nhân Viên");

        sTextField4.setForeground(new java.awt.Color(0, 0, 153));
        sTextField4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        sTextField4.sets_BgColor(new java.awt.Color(203, 224, 255));
        sTextField4.sets_placeholder("Mời Bạn Nhập");
        sTextField4.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        sTextField4.sets_placeholderForeGround(new java.awt.Color(204, 0, 204));

        lblDiaChi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDiaChi.setText("Ghi Chú");

        lblNgayMua.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNgayMua.setText("Ngày Mua");

        txtNHenTra.setForeground(new java.awt.Color(0, 0, 153));
        txtNHenTra.setDateFormatString("dd-MM-yyyy");
        txtNHenTra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblMaHDXuat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMaHDXuat.setText("Mã HĐ Xuất");

        sTextField5.setForeground(new java.awt.Color(0, 0, 153));
        sTextField5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        sTextField5.sets_BgColor(new java.awt.Color(203, 224, 255));
        sTextField5.sets_placeholder("Mời Bạn Nhập");
        sTextField5.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        sTextField5.sets_placeholderForeGround(new java.awt.Color(204, 0, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTenKhoHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSDT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(sTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblMaHDXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMaKH))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(cbbKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(210, 210, 210))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(462, 462, 462)
                        .addComponent(sButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNgayMua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaPhieuBaoHanh)
                            .addComponent(lblDiaChi))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNHenTra, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(sTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblTenKhoHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaHDXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lblMaPhieuBaoHanh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNHenTra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNgayMua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120)
                .addComponent(sButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1133, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbbKhachHangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbKhachHangItemStateChanged
        //        if (cbbKhachHang.getItemCount() > 0) {
            //            String cbb = cbbKhachHang.getSelectedItem().toString();
            //            KhachHang kh = BLLKhachHang.LayKhachHangTheoTen(cbb);
            //            if (kh != null) {
                //                txtCMND.setText(kh.getSoCMND());
                //                txtSDT.setText(kh.getSDT());
                //            }
            //        }
    }//GEN-LAST:event_cbbKhachHangItemStateChanged

    private void sButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButton1ActionPerformed
        // TODO add your handling code here:
        //        int index1 = tabChuongTrinh.indexOfTab("Quản lý khách hàng");
        //        if (index1 > 0) {
            //            tabChuongTrinh.setSelectedIndex(index1);
            //        } else {
            //
            //            TabKhachHang kh = new TabKhachHang();
            //
            //            tabChuongTrinh.add(kh, "Quản lý khách hàng");
            //
            //            int index = tabChuongTrinh.indexOfTab("Quản lý khách hàng");
            //            JPanel pnlTab = new JPanel(new GridBagLayout());
            //            pnlTab.setOpaque(false);
            //            JLabel lblTitle = new JLabel("Quản lý khách hàng");
            //            JButton btnClose = new JButton("x");
            //
            //            GridBagConstraints gbc = new GridBagConstraints();
            //            gbc.gridx = 0;
            //            gbc.gridy = 0;
            //            gbc.weightx = 1;
            //
            //            pnlTab.add(lblTitle, gbc);
            //
            //            gbc.gridx++;
            //            gbc.weightx = 0;
            //            pnlTab.add(btnClose, gbc);
            //
            //            tabChuongTrinh.setTabComponentAt(index, pnlTab);
            //            btnClose.addActionListener(new ActionListener() {
                //                @Override
                //                public void actionPerformed(ActionEvent e) {
                    //                    System.out.println(index);
                    //                    int nowIndex = tabChuongTrinh.indexOfTab("Quản lý khách hàng");
                    //                    tabChuongTrinh.remove(nowIndex);
                    //                }
                //            });
        //
        //            tabChuongTrinh.setSelectedIndex(index);
        //        }
        String MaBH = txtMa.getText();
        String MaNV = txtMaNV.getText();
        Date NgayHenTra = txtNHenTra.getDate();
        
        PhieuTNBH bh = new PhieuTNBH();
        
        bh.setMaPTN(MaBH);
        bh.setMaNV(MaNV);
        bh.setNgayHenTra(NgayHenTra);
        
        System.out.println(bh.getMaPTN());
        System.out.println(bh.getMaNV());
        System.out.println(bh.getNgayHenTra());
        
        BLLBaoHanh.ThemPTNBH(bh);
        
        
    }//GEN-LAST:event_sButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbKhachHang;
    private javax.swing.JPanel jPanel4;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblMaHDXuat;
    private javax.swing.JLabel lblMaKH;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblMaPhieuBaoHanh;
    private javax.swing.JLabel lblNgayMua;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTenKhoHang;
    private com.shady.scontrols.SButton sButton1;
    private com.shady.scontrols.STextField sTextField2;
    private com.shady.scontrols.STextField sTextField4;
    private com.shady.scontrols.STextField sTextField5;
    private com.shady.scontrols.STextField txtGhiChu;
    private com.shady.scontrols.STextField txtMa;
    private com.shady.scontrols.STextField txtMaNV;
    private com.toedter.calendar.JDateChooser txtNHenTra;
    // End of variables declaration//GEN-END:variables
}
