/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Du_An_DESIGN;

import Du_An_BLL.BLLBaoHanh;
import Du_An_DAL.DALBaoHanh;
import Du_An_DTO.PhieuTNBH;
import Du_An_HELPER.ChuyenDoi;
import Du_An_HELPER.SQLHelper;
import java.util.Date;
import java.util.Hashtable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author LENOVO
 */
public class TabCTBH extends javax.swing.JPanel {

    /**
     * Creates new form TabCTBH
     */
    public TabCTBH() {
        initComponents();
        txtTenNV.setText(frmLogin.nv.getTenNV());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel2 = new keeptoo.KGradientPanel();
        tabCheckBH = new javax.swing.JTabbedPane();
        tabPen1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new com.shady.scontrols.STable();
        lblTenNhaCC = new javax.swing.JLabel();
        txtCheckBH = new com.shady.scontrols.STextField();
        SbtnThem = new com.shady.scontrols.SButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblTenHD4 = new javax.swing.JLabel();
        txtTenKH = new com.shady.scontrols.STextField();
        lblTenHD5 = new javax.swing.JLabel();
        lblTenHD6 = new javax.swing.JLabel();
        lblTenHD7 = new javax.swing.JLabel();
        txtLyDoLoi = new com.shady.scontrols.STextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTNBH = new com.shady.scontrols.STable();
        SbtnXuatPhieuTraBH = new com.shady.scontrols.SButton();
        txtTenNV = new com.shady.scontrols.STextField();
        lblTenHD8 = new javax.swing.JLabel();
        txtSoLuong = new com.shady.scontrols.STextField();
        txtNHenTra = new com.toedter.calendar.JDateChooser();

        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(203, 224, 255));

        tabCheckBH.setBackground(new java.awt.Color(203, 224, 255));
        tabCheckBH.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tabPen1.setBackground(new java.awt.Color(203, 224, 255));
        tabPen1.setOpaque(false);

        jPanel3.setBackground(new java.awt.Color(203, 224, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phiếu Tiếp Nhận Bảo Hành", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(0, 0, 153))); // NOI18N
        jPanel1.setOpaque(false);

        tblDanhSach.setBackground(new java.awt.Color(203, 224, 255));
        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "MaSP", "Tên SP", "Thời Gian BH", "Ngày mua SP", "MaKH", "MaHDXuất", "TenKH", "MaPBH", "Tên Kho Hàng", "Địa chỉ kho hàng", "SDT Kho Hàng", "Tên NV "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSach.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSach);
        if (tblDanhSach.getColumnModel().getColumnCount() > 0) {
            tblDanhSach.getColumnModel().getColumn(0).setMinWidth(50);
            tblDanhSach.getColumnModel().getColumn(0).setMaxWidth(50);
            tblDanhSach.getColumnModel().getColumn(1).setMinWidth(0);
            tblDanhSach.getColumnModel().getColumn(1).setMaxWidth(0);
            tblDanhSach.getColumnModel().getColumn(5).setMinWidth(0);
            tblDanhSach.getColumnModel().getColumn(5).setMaxWidth(0);
            tblDanhSach.getColumnModel().getColumn(6).setMinWidth(0);
            tblDanhSach.getColumnModel().getColumn(6).setMaxWidth(0);
        }

        lblTenNhaCC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTenNhaCC.setForeground(new java.awt.Color(0, 0, 153));
        lblTenNhaCC.setText("Nhập Tên Khách Hàng / SĐT Khách Hàng");

        txtCheckBH.setForeground(new java.awt.Color(0, 0, 153));
        txtCheckBH.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCheckBH.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtCheckBH.sets_placeholder("Mời Bạn Nhập");
        txtCheckBH.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtCheckBH.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtCheckBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckBHActionPerformed(evt);
            }
        });

        SbtnThem.setForeground(new java.awt.Color(0, 0, 153));
        SbtnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/click.png"))); // NOI18N
        SbtnThem.setText("Kiểm Tra");
        SbtnThem.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SbtnThem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SbtnThem.setIconTextGap(20);
        SbtnThem.setMargin(new java.awt.Insets(5, 14, 5, 14));
        SbtnThem.setMaximumSize(new java.awt.Dimension(70, 30));
        SbtnThem.sets_borderColor(new java.awt.Color(153, 0, 153));
        SbtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCheckBH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTenNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(SbtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTenNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCheckBH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SbtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout tabPen1Layout = new javax.swing.GroupLayout(tabPen1);
        tabPen1.setLayout(tabPen1Layout);
        tabPen1Layout.setHorizontalGroup(
            tabPen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tabPen1Layout.setVerticalGroup(
            tabPen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabCheckBH.addTab("Check Bảo Hành SP", tabPen1);

        jPanel2.setBackground(new java.awt.Color(203, 224, 255));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phiếu Tiếp Nhận Bảo Hành", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(0, 0, 153))); // NOI18N
        jPanel5.setOpaque(false);

        lblTenHD4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTenHD4.setForeground(new java.awt.Color(0, 0, 255));
        lblTenHD4.setText("Tên Khách Hàng");

        txtTenKH.setForeground(new java.awt.Color(0, 0, 153));
        txtTenKH.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTenKH.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtTenKH.sets_placeholder("Mời Bạn Nhập");
        txtTenKH.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtTenKH.sets_placeholderForeGround(new java.awt.Color(204, 0, 204));

        lblTenHD5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTenHD5.setForeground(new java.awt.Color(0, 0, 255));
        lblTenHD5.setText("Tên Nhân Viên");

        lblTenHD6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTenHD6.setForeground(new java.awt.Color(0, 0, 255));
        lblTenHD6.setText("Ngày Hẹn Trả");

        lblTenHD7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTenHD7.setForeground(new java.awt.Color(0, 0, 255));
        lblTenHD7.setText("Lý Do Lỗi");

        txtLyDoLoi.setForeground(new java.awt.Color(0, 0, 153));
        txtLyDoLoi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtLyDoLoi.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtLyDoLoi.sets_placeholder("Mời Bạn Nhập");
        txtLyDoLoi.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtLyDoLoi.sets_placeholderForeGround(new java.awt.Color(204, 0, 204));
        txtLyDoLoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLyDoLoiActionPerformed(evt);
            }
        });

        tblTNBH.setBackground(new java.awt.Color(203, 224, 255));
        tblTNBH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã SP", "Tên SP", "Ma_HDXuat", "Ghi Chú"
            }
        ));
        jScrollPane3.setViewportView(tblTNBH);
        if (tblTNBH.getColumnModel().getColumnCount() > 0) {
            tblTNBH.getColumnModel().getColumn(0).setMinWidth(50);
            tblTNBH.getColumnModel().getColumn(0).setMaxWidth(50);
            tblTNBH.getColumnModel().getColumn(1).setMinWidth(100);
            tblTNBH.getColumnModel().getColumn(1).setMaxWidth(100);
            tblTNBH.getColumnModel().getColumn(3).setMinWidth(0);
            tblTNBH.getColumnModel().getColumn(3).setMaxWidth(0);
        }

        SbtnXuatPhieuTraBH.setForeground(new java.awt.Color(0, 0, 204));
        SbtnXuatPhieuTraBH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/nhapmoi.png"))); // NOI18N
        SbtnXuatPhieuTraBH.setText("Xuất Phiếu ");
        SbtnXuatPhieuTraBH.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        SbtnXuatPhieuTraBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnXuatPhieuTraBHActionPerformed(evt);
            }
        });

        txtTenNV.setForeground(new java.awt.Color(0, 0, 153));
        txtTenNV.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTenNV.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtTenNV.sets_placeholder("Mời Bạn Nhập");
        txtTenNV.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtTenNV.sets_placeholderForeGround(new java.awt.Color(204, 0, 204));
        txtTenNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNVActionPerformed(evt);
            }
        });

        lblTenHD8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTenHD8.setForeground(new java.awt.Color(0, 0, 255));
        lblTenHD8.setText("Số Lượng");

        txtSoLuong.setForeground(new java.awt.Color(0, 0, 153));
        txtSoLuong.setText("1");
        txtSoLuong.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSoLuong.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtSoLuong.sets_placeholder("Mời Bạn Nhập");
        txtSoLuong.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtSoLuong.sets_placeholderForeGround(new java.awt.Color(204, 0, 204));

        txtNHenTra.setForeground(new java.awt.Color(0, 0, 153));
        txtNHenTra.setDateFormatString("dd-MM-yyyy");
        txtNHenTra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SbtnXuatPhieuTraBH, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTenHD5)
                                    .addComponent(lblTenHD6)
                                    .addComponent(lblTenHD7))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLyDoLoi, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(txtNHenTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(236, 236, 236))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(lblTenHD4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(lblTenHD8)
                                        .addGap(71, 71, 71)))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(236, 236, 236)))
                        .addGap(322, 322, 322))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenHD5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblTenHD6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(txtNHenTra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenHD4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenHD8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenHD7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLyDoLoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SbtnXuatPhieuTraBH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        tabCheckBH.addTab("Phiếu Tiếp Nhận BH", jPanel2);

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabCheckBH)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabCheckBH)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1084, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public void XuatHoaDon(String Ma_PTNBH) {
        try {

            Hashtable map = new Hashtable();
            JasperReport report = JasperCompileManager.compileReport("src/Du_An_DESIGN/rptPhieuTNBH.jrxml");

            map.put("Ma_PTNBH", Ma_PTNBH);

            JasperPrint p = JasperFillManager.fillReport(report, map, SQLHelper.Connection);
            JasperViewer.viewReport(p, false);
            JasperExportManager.exportReportToPdfFile(p, "test.pdf");
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }
    private void SbtnXuatPhieuTraBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnXuatPhieuTraBHActionPerformed
        
       String MaBH = BLLBaoHanh.TaoMaPTNBH();
        String MaNV = frmLogin.nv.getMaNV();
        Date NgayHenTra = txtNHenTra.getDate();
        long millis =System.currentTimeMillis();
        java.sql.Date date= new java.sql.Date(millis);
        String LyDoLoi = txtLyDoLoi.getText();
        int SoLuong = Integer.parseInt(txtSoLuong.getText());
        String GhiChu = "";
        String MaCTBH = BLLBaoHanh.TaoMaPCTTNBH();
        
        
        
        PhieuTNBH bh = new PhieuTNBH();
        
        bh.setMaPTN(MaBH);
        bh.setMaNV(MaNV);
        bh.setNgayHenTra(date);
        
        System.out.println(bh.getMaPTN());
        System.out.println(bh.getMaNV());
        System.out.println(bh.getNgayHenTra());
        
        BLLBaoHanh.ThemPTNBH(bh);
        
        BLLBaoHanh.ThemCTTNBH(tblTNBH,MaCTBH, LyDoLoi, NgayHenTra, SoLuong, MaBH, GhiChu);
        
        bh.setMaPTN(BLLBaoHanh.GetTenHDBySoHoaDon(bh.getMaPTN()));
        //System.out.println(hdXuat.getMa_HD_Xuat());
        
        XuatHoaDon(bh.getMaPTN());
        
    }//GEN-LAST:event_SbtnXuatPhieuTraBHActionPerformed
    private void ThemSPVaotblCTHD(String MaSP, String TenSP, String Ma_HDXuat) {
        DefaultTableModel tblModel = (DefaultTableModel) tblTNBH.getModel();

        Object ojb[] = new Object[4];
        ojb[0] = tblModel.getRowCount() + 1;
        ojb[1] = MaSP;
        ojb[2] = TenSP;
        ojb[3] = Ma_HDXuat;

        tblModel.addRow(ojb);
    }
    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        if(evt.getClickCount() >= 2) {
            String MaSP = tblDanhSach.getValueAt(tblDanhSach.getSelectedRow(), 1).toString();
            String TenSP = tblDanhSach.getValueAt(tblDanhSach.getSelectedRow(), 2).toString();
            String Ma_HDXuat = tblDanhSach.getValueAt(tblDanhSach.getSelectedRow(), 6).toString();
            
            ThemSPVaotblCTHD(MaSP, TenSP, Ma_HDXuat);
            txtTenKH.setText(tblDanhSach.getValueAt(tblDanhSach.getSelectedRow(), 7).toString());
            tabCheckBH.setSelectedIndex(1);

        }
    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void txtCheckBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckBHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckBHActionPerformed

    private void SbtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnThemActionPerformed
        String TenNhanVien =  txtCheckBH.getText() ;
        String SDT =  txtCheckBH.getText() ;

        BLLBaoHanh.TimBH(tblDanhSach, SDT, TenNhanVien);
    }//GEN-LAST:event_SbtnThemActionPerformed

    private void txtTenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNVActionPerformed

    private void txtLyDoLoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLyDoLoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLyDoLoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.shady.scontrols.SButton SbtnThem;
    private com.shady.scontrols.SButton SbtnXuatPhieuTraBH;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lblTenHD4;
    private javax.swing.JLabel lblTenHD5;
    private javax.swing.JLabel lblTenHD6;
    private javax.swing.JLabel lblTenHD7;
    private javax.swing.JLabel lblTenHD8;
    private javax.swing.JLabel lblTenNhaCC;
    private javax.swing.JTabbedPane tabCheckBH;
    private javax.swing.JPanel tabPen1;
    private com.shady.scontrols.STable tblDanhSach;
    private com.shady.scontrols.STable tblTNBH;
    private com.shady.scontrols.STextField txtCheckBH;
    private com.shady.scontrols.STextField txtLyDoLoi;
    private com.toedter.calendar.JDateChooser txtNHenTra;
    private com.shady.scontrols.STextField txtSoLuong;
    private com.shady.scontrols.STextField txtTenKH;
    private com.shady.scontrols.STextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
