/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Du_An_DESIGN;

import Du_An_BLL.BLLBaoHanh;
import Du_An_BLL.BLLCTHDXuat;
import Du_An_BLL.BLLCombobox;
import Du_An_BLL.BLLHoaDonXuat;
import Du_An_BLL.BLLKhachHang;
import Du_An_BLL.BLLLoaiSP;
import Du_An_BLL.BLLNhanVien;
import Du_An_BLL.BLLSanPham;
import Du_An_DAL.DALHDXuat;
import Du_An_DAL.DALKhachHang;
import Du_An_DAL.DALLoaiSP;
import Du_An_DAL.DALNhanVien;
import static Du_An_DESIGN.TabHD_Nhap.GhiChu;
import static Du_An_DESIGN.TabHD_Nhap.Huy;
import static Du_An_DESIGN.TabHD_Nhap.SoLuongMua;
//import static Du_An_DESIGN.frmMain.tabChuongTrinh;
import Du_An_DTO.HDXuat;
import Du_An_DTO.KhachHang;
import Du_An_DTO.NhanVien;
import Du_An_DTO.PhieuBaoHanh;
import Du_An_HELPER.ChuyenDoi;
import Du_An_HELPER.HoTroNhapSo;
import Du_An_HELPER.SQLHelper;
import Du_An_HELPER.ThongBao;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.util.Date;
import java.util.Hashtable;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author LENOVO
 */
public class TabHD_Xuat extends javax.swing.JPanel {

    /**
     * Creates new form TabHD_Xuat
     */
    public TabHD_Xuat() {
        initComponents();

        BLLSanPham.LoadSanPhamHoaDonXuat(tblSanPhamHDXuat);

        

        ResultSet LoaiSP = DALLoaiSP.GetAll();
        BLLCombobox.Load(cbbChonLoaiSP, LoaiSP, true);

        ResultSet kh = DALKhachHang.getALLKhachHang();
        BLLCombobox.Load(cbbKhachHang, kh, true);

        txtMaHD.setText(BLLHoaDonXuat.TaoMaHDX());
        txtTenNV.setText(frmLogin.nv.getTenNV());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        lblTimKiemSP = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPhamHDXuat = new javax.swing.JTable();
        lblChonLoaiSP = new javax.swing.JLabel();
        cbbChonLoaiSP = new javax.swing.JComboBox<>();
        txtTuKhoaSanPham = new com.shady.scontrols.STextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCHHD = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lblTongTien = new javax.swing.JLabel();
        lblTienKhachTra = new javax.swing.JLabel();
        lblGhiChu = new javax.swing.JLabel();
        lblTienDu = new javax.swing.JLabel();
        lblGiamPt = new javax.swing.JLabel();
        lblGiamTien = new javax.swing.JLabel();
        btnThanhToan = new com.shady.scontrols.SButton();
        sButton2 = new com.shady.scontrols.SButton();
        txtGiamPt = new com.shady.scontrols.STextField();
        txtTongTien = new com.shady.scontrols.STextField();
        txtTienDu = new com.shady.scontrols.STextField();
        txtGiamTien = new com.shady.scontrols.STextField();
        txtTienKhachTra = new com.shady.scontrols.STextField();
        txtTTGhiChu = new com.shady.scontrols.STextField();
        lblNgayTaoHD = new javax.swing.JLabel();
        lblNguoiTaoHD = new javax.swing.JLabel();
        lblKhachHang = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        lblTenHD = new javax.swing.JLabel();
        cbbKhachHang = new javax.swing.JComboBox<>();
        txt_Date = new com.toedter.calendar.JDateChooser();
        txtSDT = new com.shady.scontrols.STextField();
        txtDiaChi = new com.shady.scontrols.STextField();
        txtMaHD = new com.shady.scontrols.STextField();
        txtTenNV = new com.shady.scontrols.STextField();

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkGradientFocus(600);
        kGradientPanel1.setkStartColor(new java.awt.Color(203, 224, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Sản Phẩm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel1.setOpaque(false);

        lblTimKiemSP.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblTimKiemSP.setForeground(new java.awt.Color(0, 0, 204));
        lblTimKiemSP.setText("Nhập Tên Sản Phẩm Cần Tìm");

        tblSanPhamHDXuat.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tblSanPhamHDXuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên Sản Phẩm", "Số Lượng", "Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPhamHDXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamHDXuatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPhamHDXuat);

        lblChonLoaiSP.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblChonLoaiSP.setForeground(new java.awt.Color(0, 0, 204));
        lblChonLoaiSP.setText("Chọn Loại Sản Phẩm");

        cbbChonLoaiSP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbbChonLoaiSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbChonLoaiSP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbChonLoaiSPItemStateChanged(evt);
            }
        });
        cbbChonLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbChonLoaiSPActionPerformed(evt);
            }
        });

        txtTuKhoaSanPham.setForeground(new java.awt.Color(0, 0, 204));
        txtTuKhoaSanPham.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTuKhoaSanPham.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtTuKhoaSanPham.sets_placeholder("Nhập Tên Sản Phẩm Cần Tìm");
        txtTuKhoaSanPham.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtTuKhoaSanPham.sets_placeholderForeGround(new java.awt.Color(153, 0, 204));
        txtTuKhoaSanPham.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTuKhoaSanPhamKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblChonLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbbChonLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTuKhoaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTimKiemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTimKiemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtTuKhoaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblChonLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(cbbChonLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1)
                .addGap(20, 20, 20))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thanh Toán", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel4.setOpaque(false);

        tblCHHD.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tblCHHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng Mua", "Giá", "Thành Tiền", "Ghi Chú"
            }
        ));
        jScrollPane2.setViewportView(tblCHHD);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sự Kiện Của Hoá Đơn", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel3.setOpaque(false);

        lblTongTien.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblTongTien.setForeground(new java.awt.Color(0, 0, 204));
        lblTongTien.setText("Tổng Tiền");

        lblTienKhachTra.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblTienKhachTra.setForeground(new java.awt.Color(0, 0, 204));
        lblTienKhachTra.setText("Tiền Khách Trả ");

        lblGhiChu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGhiChu.setForeground(new java.awt.Color(0, 0, 204));
        lblGhiChu.setText("Ghi Chú");

        lblTienDu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTienDu.setForeground(new java.awt.Color(0, 0, 204));
        lblTienDu.setText("Tiền dư");

        lblGiamPt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGiamPt.setForeground(new java.awt.Color(0, 0, 204));
        lblGiamPt.setText("Giảm %");

        lblGiamTien.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGiamTien.setForeground(new java.awt.Color(0, 0, 204));
        lblGiamTien.setText("Giảm tiền");

        btnThanhToan.setForeground(new java.awt.Color(0, 0, 204));
        btnThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/hoadon.png"))); // NOI18N
        btnThanhToan.setText("Thanh Toán");
        btnThanhToan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        sButton2.setForeground(new java.awt.Color(0, 0, 204));
        sButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/nhapmoi.png"))); // NOI18N
        sButton2.setText("Tạo HĐ Mới");
        sButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        sButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButton2ActionPerformed(evt);
            }
        });

        txtGiamPt.setForeground(new java.awt.Color(0, 0, 204));
        txtGiamPt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtGiamPt.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtGiamPt.sets_placeholder("Mời Bạn Nhập");
        txtGiamPt.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtGiamPt.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtGiamPt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGiamPtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGiamPtKeyReleased(evt);
            }
        });

        txtTongTien.setEditable(false);
        txtTongTien.setForeground(new java.awt.Color(0, 0, 204));
        txtTongTien.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTongTien.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtTongTien.sets_placeholder("");
        txtTongTien.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtTongTien.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtTongTien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTongTienKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTongTienKeyReleased(evt);
            }
        });

        txtTienDu.setEditable(false);
        txtTienDu.setForeground(new java.awt.Color(0, 0, 204));
        txtTienDu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTienDu.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtTienDu.sets_placeholder("");
        txtTienDu.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtTienDu.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtTienDu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTienDuKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienDuKeyReleased(evt);
            }
        });

        txtGiamTien.setForeground(new java.awt.Color(0, 0, 204));
        txtGiamTien.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtGiamTien.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtGiamTien.sets_placeholder("Mời Bạn Nhập");
        txtGiamTien.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtGiamTien.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtGiamTien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGiamTienKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGiamTienKeyReleased(evt);
            }
        });

        txtTienKhachTra.setForeground(new java.awt.Color(0, 0, 204));
        txtTienKhachTra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTienKhachTra.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtTienKhachTra.sets_placeholder("Mời Bạn Nhập");
        txtTienKhachTra.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtTienKhachTra.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtTienKhachTra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTienKhachTraKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienKhachTraKeyReleased(evt);
            }
        });

        txtTTGhiChu.setForeground(new java.awt.Color(0, 0, 204));
        txtTTGhiChu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTTGhiChu.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtTTGhiChu.sets_placeholder("Mời Bạn Nhập");
        txtTTGhiChu.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtTTGhiChu.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTienDu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGiamPt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiamPt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTienDu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblGiamTien, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGiamTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTienKhachTra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTienKhachTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTTGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblGiamPt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(txtGiamPt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblGiamTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtGiamTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTienKhachTra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTienKhachTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTTGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTienDu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTienDu, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        lblNgayTaoHD.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNgayTaoHD.setText("Ngày tạo");

        lblNguoiTaoHD.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNguoiTaoHD.setText("Người tạo HĐ");

        lblKhachHang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblKhachHang.setText("Khách Hàng");

        lblDiaChi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDiaChi.setText("Địa Chỉ");

        lblSDT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSDT.setText("SĐT");

        lblTenHD.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTenHD.setText("Mã HĐ");

        cbbKhachHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbKhachHang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbKhachHangItemStateChanged(evt);
            }
        });

        txt_Date.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        txt_Date.setForeground(new java.awt.Color(0, 0, 153));
        txt_Date.setToolTipText("");
        txt_Date.setDate(new java.util.Date(1609125634000L));
        txt_Date.setDateFormatString("dd-MM-yyyy");
        txt_Date.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        txtSDT.setEditable(false);
        txtSDT.setForeground(new java.awt.Color(0, 0, 153));
        txtSDT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSDT.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtSDT.sets_placeholder("............");
        txtSDT.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtSDT.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSDTKeyPressed(evt);
            }
        });

        txtDiaChi.setEditable(false);
        txtDiaChi.setForeground(new java.awt.Color(0, 0, 153));
        txtDiaChi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDiaChi.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtDiaChi.sets_placeholder("............");
        txtDiaChi.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtDiaChi.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));

        txtMaHD.setEditable(false);
        txtMaHD.setForeground(new java.awt.Color(0, 0, 204));
        txtMaHD.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMaHD.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtMaHD.sets_placeholder("");
        txtMaHD.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtMaHD.sets_placeholderForeGround(new java.awt.Color(255, 0, 255));

        txtTenNV.setEditable(false);
        txtTenNV.setForeground(new java.awt.Color(0, 0, 204));
        txtTenNV.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTenNV.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtTenNV.sets_placeholder("");
        txtTenNV.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtTenNV.sets_placeholderForeGround(new java.awt.Color(255, 0, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblNgayTaoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(txt_Date, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(cbbKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNguoiTaoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTenHD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaHD, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNguoiTaoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNgayTaoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1222, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    private void tblSanPhamHDXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamHDXuatMouseClicked
        if (evt.getClickCount() >= 2) {
            jdlThongTinSanPham jdl = new jdlThongTinSanPham((JFrame) SwingUtilities.getWindowAncestor(this), true);
            jdl.setVisible(true);
            if (Huy) {
                return;
            }
            // Lấy IDSanPham <=> Lấy sản phẩm theo ID

            String MaSP = tblSanPhamHDXuat.getValueAt(tblSanPhamHDXuat.getSelectedRow(), 0).toString();
            String TenSP = tblSanPhamHDXuat.getValueAt(tblSanPhamHDXuat.getSelectedRow(), 1).toString();
            double DonGia = Double.parseDouble(tblSanPhamHDXuat.getValueAt(tblSanPhamHDXuat.getSelectedRow(), 3).toString());
            double ThanhTien = DonGia * SoLuongMua;

            ThemSPVaotblCTHD(MaSP, TenSP, SoLuongMua, DonGia, ThanhTien, GhiChu);

            double tongTien = TinhTien();
            double tienDu;

            double giamPT;
            double giamTien;

            if (txtGiamPt.getText().isEmpty()) {
                giamPT = 0;
            } else {
                giamPT = Double.parseDouble(txtGiamPt.getText());
            }

            if (txtGiamTien.getText().isEmpty()) {
                giamTien = 0;
            } else {
                giamTien = Double.parseDouble(txtGiamTien.getText());
            }

            double tongTienFinal = tongTien - ((tongTien * giamPT) / 100) - giamTien;
            txtTongTien.setText(ChuyenDoi.LaySoString(tongTienFinal));

            if (txtTienKhachTra.getText().isEmpty()) {
                tienDu = 0;
            } else {
                double tienKhachTra = Double.parseDouble(txtTienKhachTra.getText());
                tienDu = tienKhachTra - tongTienFinal;
            }
            txtTienDu.setText(ChuyenDoi.LaySoString(tienDu));
        }
    }//GEN-LAST:event_tblSanPhamHDXuatMouseClicked

    private void ThemSPVaotblCTHD(String MaSP, String TenSP, double SoLuong, double DonGia, double ThanhTien, String GhiChu) {
        DefaultTableModel tblModel = (DefaultTableModel) tblCHHD.getModel();

        Object ojb[] = new Object[7];
        ojb[0] = tblModel.getRowCount() + 1;
        ojb[1] = MaSP;
        ojb[2] = TenSP;
        ojb[3] = SoLuong;
        ojb[4] = ChuyenDoi.DinhDangTien(DonGia);
        ojb[5] = ChuyenDoi.DinhDangTien(ThanhTien);
        ojb[6] = GhiChu;

        tblModel.addRow(ojb);
    }

    private double TinhTien() {
        double tongTien = 0;
        for (int i = 0; i < tblCHHD.getRowCount(); i++) {
            tongTien += ChuyenDoi.ChuyenTien(tblCHHD.getValueAt(i, 5).toString());
        }

        return tongTien;
    }

    private void cbbChonLoaiSPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbChonLoaiSPItemStateChanged
        if (cbbChonLoaiSP.getSelectedIndex() > 0) {
            String tenLoaiSP = cbbChonLoaiSP.getSelectedItem().toString();
            String maLoaiSP = BLLLoaiSP.GetMaLSPByTenLSP(tenLoaiSP);

            String keyWord = txtTuKhoaSanPham.getText();
            if (keyWord.isEmpty()) {
                BLLSanPham.LocDSSPTheoMaLoaiSP(tblSanPhamHDXuat, maLoaiSP);
            } else {
                BLLSanPham.LocDSSP(tblSanPhamHDXuat, keyWord, maLoaiSP);
            }
        } else {
            BLLSanPham.LoadSanPhamHoaDonXuat(tblSanPhamHDXuat);
        }
    }//GEN-LAST:event_cbbChonLoaiSPItemStateChanged

    private void cbbChonLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbChonLoaiSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbChonLoaiSPActionPerformed

    private void cbbKhachHangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbKhachHangItemStateChanged
        if (cbbKhachHang.getItemCount() > 0) {
            String tenKH = cbbKhachHang.getSelectedItem().toString();
            KhachHang kh = BLLKhachHang.LayKhachHangTheoTen(tenKH);
            if (kh != null) {
                txtDiaChi.setText(kh.getDiaChi());
                txtSDT.setText(kh.getSDT());
            }
        }
    }//GEN-LAST:event_cbbKhachHangItemStateChanged

    private void txtTuKhoaSanPhamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTuKhoaSanPhamKeyReleased
        String keyWord = txtTuKhoaSanPham.getText();

        if (cbbChonLoaiSP.getSelectedIndex() > 0) {
            String tenLoaiSP = cbbChonLoaiSP.getSelectedItem().toString();
            String maLoaiSP = BLLLoaiSP.GetMaLSPByTenLSP(tenLoaiSP);

            BLLSanPham.LocDSSP(tblSanPhamHDXuat, keyWord, maLoaiSP);
        } else {
            BLLSanPham.LocDSSPTheoKeyWord(tblSanPhamHDXuat, keyWord);
        }
    }//GEN-LAST:event_txtTuKhoaSanPhamKeyReleased
    public void XuatHoaDon(String Ma_HD_Xuat) {
        try {

            Hashtable map = new Hashtable();
            JasperReport report = JasperCompileManager.compileReport("src/Du_An_DESIGN/rptHoaDonXuat.jrxml");

            map.put("Ma_HD_Xuat", Ma_HD_Xuat);

            JasperPrint p = JasperFillManager.fillReport(report, map, SQLHelper.Connection);
            JasperViewer.viewReport(p, false);
            JasperExportManager.exportReportToPdfFile(p, "test.pdf");
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        if (tblCHHD.getRowCount() <= 0) {
            ThongBao.ThongBaoDangNhap("Thông báo", "Chưa chọn sản phẩm");
            return;
        }

        

        if (cbbKhachHang.getSelectedIndex() <= 0) {
            ThongBao.ThongBaoDangNhap("Thông báo", "Chưa chọn Khách Hàng");
            return;
        }

        String tenNV = txtTenNV.getText();
        NhanVien nv = BLLNhanVien.LayNVTheoTen(tenNV);
        String maNV = nv.getMaNV();

        String tenKH = cbbKhachHang.getSelectedItem().toString();
        KhachHang kh = BLLKhachHang.LayKhachHangTheoTen(tenKH);
        String maKH = kh.getMaKhachHang();

        String maHD = txtMaHD.getText();

        HDXuat hdXuat = new HDXuat();
        hdXuat.setMa_HD_Xuat(maHD);
        hdXuat.setNgayTao(txt_Date.getDate());
        hdXuat.setMaNV(maNV);
        hdXuat.setMaKH(maKH);
        hdXuat.setTongTien(ChuyenDoi.LaySoDouble(txtTongTien.getText()));
        hdXuat.setGhiChu(txtTTGhiChu.getText());

        DALHDXuat.ThemHDXuat(hdXuat);

        BLLCTHDXuat.ThemCTHDXuat(tblCHHD, maHD);

      
        
        hdXuat.setMa_HD_Xuat(BLLHoaDonXuat.GetTenHDBySoHoaDon(hdXuat.getMa_HD_Xuat()));
        //System.out.println(hdXuat.getMa_HD_Xuat());
        
        
        XuatHoaDon(hdXuat.getMa_HD_Xuat());
        
        
        String MaPBH = BLLBaoHanh.TaoMaPBH();
        String TenKH = "Kho Hàng 113 ";
        String DiaChiKH = "BMT";
        String SDTKH = "0378598564";
        Date NgayMuaSp = txt_Date.getDate();
        
        PhieuBaoHanh bh = new PhieuBaoHanh();
        bh.setMaPBH(MaPBH);
        bh.setTenKhoHang(TenKH);
        bh.setDiaChiKhoHang(DiaChiKH);
        bh.setSDTKhoHang(SDTKH);
        bh.setMaNV(maNV);
        bh.setMaKH(maKH);
        bh.setMaHDXuat(maHD);
        bh.setNgayMuaSP(NgayMuaSp);
        
        BLLBaoHanh.ThemPBH(bh);
        
        
        
        
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void sButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButton2ActionPerformed
        cbbKhachHang.setSelectedIndex(0);
        txtDiaChi.setText("");
        txtSDT.setText("");
        txtTTGhiChu.setText("");
        txtMaHD.setText(BLLHoaDonXuat.TaoMaHDX());
        txtTongTien.setText("");
        txtGiamPt.setText("");
        txtGiamTien.setText("");
        txtTienDu.setText("");
        txtTienKhachTra.setText("");

        DefaultTableModel tbl = (DefaultTableModel) tblCHHD.getModel();
        for (int i = tbl.getRowCount() - 1; i >= 0; i--) {
            tbl.removeRow(i);
        }


    }//GEN-LAST:event_sButton2ActionPerformed

    private void txtGiamPtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiamPtKeyPressed
        HoTroNhapSo.luonNhapSo(evt);
    }//GEN-LAST:event_txtGiamPtKeyPressed

    private void txtGiamPtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiamPtKeyReleased
        double tongTien = TinhTien();
        double tienDu;

        double giamPT;
        double giamTien;

        if (txtGiamPt.getText().isEmpty()) {
            giamPT = 0;
        } else {
            giamPT = Double.parseDouble(txtGiamPt.getText());
        }

        if (txtGiamTien.getText().isEmpty()) {
            giamTien = 0;
        } else {
            giamTien = Double.parseDouble(txtGiamTien.getText());
        }

        double tongTienFinal = tongTien - ((tongTien * giamPT) / 100) - giamTien;
        txtTongTien.setText(ChuyenDoi.LaySoString(tongTienFinal));

        if (txtTienKhachTra.getText().isEmpty()) {
            tienDu = 0;
        } else {
            double tienKhachTra = Double.parseDouble(txtTienKhachTra.getText());
            tienDu = tienKhachTra - tongTienFinal;
        }
        txtTienDu.setText(ChuyenDoi.LaySoString(tienDu));
    }//GEN-LAST:event_txtGiamPtKeyReleased

    private void txtTongTienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTongTienKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienKeyPressed

    private void txtTongTienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTongTienKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienKeyReleased

    private void txtTienDuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienDuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienDuKeyPressed

    private void txtTienDuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienDuKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienDuKeyReleased

    private void txtGiamTienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiamTienKeyPressed
        HoTroNhapSo.luonNhapSo(evt);
    }//GEN-LAST:event_txtGiamTienKeyPressed

    private void txtGiamTienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiamTienKeyReleased
        double tongTien = TinhTien();
        double tienDu;

        double giamPT;
        double giamTien;

        if (txtGiamPt.getText().isEmpty()) {
            giamPT = 0;
        } else {
            giamPT = Double.parseDouble(txtGiamPt.getText());
        }

        if (txtGiamTien.getText().isEmpty()) {
            giamTien = 0;
        } else {
            giamTien = Double.parseDouble(txtGiamTien.getText());
        }

        double tongTienFinal = tongTien - ((tongTien * giamPT) / 100) - giamTien;
        txtTongTien.setText(ChuyenDoi.LaySoString(tongTienFinal));

        if (txtTienKhachTra.getText().isEmpty()) {
            tienDu = 0;
        } else {
            double tienKhachTra = Double.parseDouble(txtTienKhachTra.getText());
            tienDu = tienKhachTra - tongTienFinal;
        }
        txtTienDu.setText(ChuyenDoi.LaySoString(tienDu));
    }//GEN-LAST:event_txtGiamTienKeyReleased

    private void txtTienKhachTraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachTraKeyReleased
        double tongTien = TinhTien();
        double tienDu;

        double giamPT;
        double giamTien;

        if (txtGiamPt.getText().isEmpty()) {
            giamPT = 0;
        } else {
            giamPT = Double.parseDouble(txtGiamPt.getText());
        }

        if (txtGiamTien.getText().isEmpty()) {
            giamTien = 0;
        } else {
            giamTien = Double.parseDouble(txtGiamTien.getText());
        }

        double tongTienFinal = tongTien - ((tongTien * giamPT) / 100) - giamTien;
        txtTongTien.setText(ChuyenDoi.LaySoString(tongTienFinal));

        if (txtTienKhachTra.getText().isEmpty()) {
            tienDu = 0;
        } else {
            double tienKhachTra = Double.parseDouble(txtTienKhachTra.getText());
            tienDu = tienKhachTra - tongTienFinal;
        }
        txtTienDu.setText(ChuyenDoi.LaySoString(tienDu));
    }//GEN-LAST:event_txtTienKhachTraKeyReleased

    private void txtSDTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSDTKeyPressed
        HoTroNhapSo.luonNhapSo(evt);
    }//GEN-LAST:event_txtSDTKeyPressed

    private void txtTienKhachTraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachTraKeyPressed
        HoTroNhapSo.luonNhapSo(evt);
    }//GEN-LAST:event_txtTienKhachTraKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.shady.scontrols.SButton btnThanhToan;
    private javax.swing.JComboBox<String> cbbChonLoaiSP;
    private javax.swing.JComboBox<String> cbbKhachHang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblChonLoaiSP;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblGiamPt;
    private javax.swing.JLabel lblGiamTien;
    private javax.swing.JLabel lblKhachHang;
    private javax.swing.JLabel lblNgayTaoHD;
    private javax.swing.JLabel lblNguoiTaoHD;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTenHD;
    private javax.swing.JLabel lblTienDu;
    private javax.swing.JLabel lblTienKhachTra;
    private javax.swing.JLabel lblTimKiemSP;
    private javax.swing.JLabel lblTongTien;
    private com.shady.scontrols.SButton sButton2;
    private javax.swing.JTable tblCHHD;
    private javax.swing.JTable tblSanPhamHDXuat;
    private com.shady.scontrols.STextField txtDiaChi;
    private com.shady.scontrols.STextField txtGiamPt;
    private com.shady.scontrols.STextField txtGiamTien;
    private com.shady.scontrols.STextField txtMaHD;
    private com.shady.scontrols.STextField txtSDT;
    private com.shady.scontrols.STextField txtTTGhiChu;
    private com.shady.scontrols.STextField txtTenNV;
    private com.shady.scontrols.STextField txtTienDu;
    private com.shady.scontrols.STextField txtTienKhachTra;
    private com.shady.scontrols.STextField txtTongTien;
    private com.shady.scontrols.STextField txtTuKhoaSanPham;
    private com.toedter.calendar.JDateChooser txt_Date;
    // End of variables declaration//GEN-END:variables
}
