/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Du_An_DESIGN;

import Du_An_BLL.BLLCTHDNhap;
import Du_An_BLL.BLLCombobox;
import Du_An_BLL.BLLHoaDonNhap;
import Du_An_BLL.BLLLoaiSP;
import Du_An_BLL.BLLNhaCC;
import Du_An_BLL.BLLNhanVien;
import Du_An_BLL.BLLSanPham;
import Du_An_DAL.DALHDNhap;
import Du_An_DAL.DALLoaiSP;
import Du_An_DAL.DALNhaCC;
import Du_An_DAL.DALNhanVien;
import Du_An_DTO.HDNhap;
import Du_An_DTO.NhaCC;
import Du_An_DTO.NhanVien;
import Du_An_HELPER.ChuyenDoi;
import Du_An_HELPER.SQLHelper;
import Du_An_HELPER.ThongBao;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.util.Hashtable;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author LENOVO
 */
public class TabHD_Nhap extends javax.swing.JPanel {
    
    public TabHD_Nhap() {
        initComponents();
        
        BLLSanPham.LoadSanPhamHoaDon(tblSanPham);

        

        ResultSet LoaiSP = DALLoaiSP.GetAll();
        BLLCombobox.Load(cbbChonLoaiSP, LoaiSP, true);

        ResultSet ncc = DALNhaCC.getALLNCC();
        BLLCombobox.Load(cbbNCC, ncc, true);
        
        txtMaHD.setText(BLLHoaDonNhap.TaoMaHDN());
        txtTenNV.setText(frmLogin.nv.getTenNV());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        lblTimKiemSP = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        lblChonLoaiSP = new javax.swing.JLabel();
        cbbChonLoaiSP = new javax.swing.JComboBox<>();
        txtTuKhoaSanPham = new com.shady.scontrols.STextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCHHD = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lblTongTien = new javax.swing.JLabel();
        lblGhiChu = new javax.swing.JLabel();
        txtTongTien = new com.shady.scontrols.STextField();
        txtTTGhiChu = new com.shady.scontrols.STextField();
        btnNewHD = new com.shady.scontrols.SButton();
        btnThanhToan = new com.shady.scontrols.SButton();
        lblNgayTaoHD = new javax.swing.JLabel();
        lblNguoiTaoHD = new javax.swing.JLabel();
        lblNhaCungCap = new javax.swing.JLabel();
        txt_Date = new com.toedter.calendar.JDateChooser();
        cbbNCC = new javax.swing.JComboBox<>();
        lblSDTNCC = new javax.swing.JLabel();
        lblDiaChiNCC = new javax.swing.JLabel();
        lblTenHD = new javax.swing.JLabel();
        txtMaHD = new com.shady.scontrols.STextField();
        txtSDT = new com.shady.scontrols.STextField();
        txtDiaChi = new com.shady.scontrols.STextField();
        txtTenNV = new com.shady.scontrols.STextField();

        kGradientPanel1.setkEndColor(new java.awt.Color(203, 224, 255));
        kGradientPanel1.setkGradientFocus(600);
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Sản Phẩm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 13), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel1.setOpaque(false);

        lblTimKiemSP.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblTimKiemSP.setForeground(new java.awt.Color(0, 0, 204));
        lblTimKiemSP.setText("Nhập Tên Sản Phẩm Cần Tìm");

        tblSanPham.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên Sản Phẩm", "Số Lượng", "Giá Nhập"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);

        lblChonLoaiSP.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblChonLoaiSP.setForeground(new java.awt.Color(0, 0, 204));
        lblChonLoaiSP.setText("Chọn Loại Sản Phẩm");

        cbbChonLoaiSP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbbChonLoaiSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbChonLoaiSP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbChonLoaiSPItemStateChanged(evt);
            }
        });
        cbbChonLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbChonLoaiSPActionPerformed(evt);
            }
        });

        txtTuKhoaSanPham.setForeground(new java.awt.Color(0, 0, 153));
        txtTuKhoaSanPham.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTuKhoaSanPham.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtTuKhoaSanPham.sets_placeholder("Nhập Tên Sản Phẩm Cần Tìm");
        txtTuKhoaSanPham.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtTuKhoaSanPham.sets_placeholderForeGround(new java.awt.Color(204, 0, 204));
        txtTuKhoaSanPham.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTuKhoaSanPhamKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTimKiemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblChonLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbbChonLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTuKhoaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTimKiemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTuKhoaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblChonLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbChonLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thanh Toán", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 13), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel4.setOpaque(false);

        tblCHHD.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tblCHHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã SP", "Tên Sản Phẩm", "Số Lượng ", "Giá", "Thành Tiền", "Ghi Chú"
            }
        ));
        jScrollPane2.setViewportView(tblCHHD);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sự Kiện Của Hoá Đơn", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 13), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel3.setOpaque(false);

        lblTongTien.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblTongTien.setForeground(new java.awt.Color(0, 0, 204));
        lblTongTien.setText("Tổng Tiền");

        lblGhiChu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGhiChu.setForeground(new java.awt.Color(0, 0, 204));
        lblGhiChu.setText("Ghi Chú");

        txtTongTien.setForeground(new java.awt.Color(0, 0, 153));
        txtTongTien.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTongTien.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtTongTien.sets_placeholder("");
        txtTongTien.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtTongTien.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));

        txtTTGhiChu.setForeground(new java.awt.Color(0, 0, 153));
        txtTTGhiChu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTTGhiChu.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtTTGhiChu.sets_placeholder("Mời Bạn Nhập");
        txtTTGhiChu.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtTTGhiChu.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));

        btnNewHD.setForeground(new java.awt.Color(0, 0, 153));
        btnNewHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/nhapmoi.png"))); // NOI18N
        btnNewHD.setText("Tạo HĐ Mới");
        btnNewHD.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNewHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewHDActionPerformed(evt);
            }
        });

        btnThanhToan.setForeground(new java.awt.Color(0, 0, 153));
        btnThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/hoadon.png"))); // NOI18N
        btnThanhToan.setText("Thanh Toán");
        btnThanhToan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNewHD, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTTGhiChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTTGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        lblNgayTaoHD.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNgayTaoHD.setText("Ngày tạo");

        lblNguoiTaoHD.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNguoiTaoHD.setText("Người tạo HĐ");

        lblNhaCungCap.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNhaCungCap.setText("Nhà Cung Cấp");

        txt_Date.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        txt_Date.setForeground(new java.awt.Color(0, 0, 153));
        txt_Date.setToolTipText("");
        txt_Date.setDate(new java.util.Date(1609125634000L));
        txt_Date.setDateFormatString("dd-MM-yyyy");
        txt_Date.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        cbbNCC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbbNCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbNCC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbNCCItemStateChanged(evt);
            }
        });
        cbbNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbbNCCMouseReleased(evt);
            }
        });
        cbbNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNCCActionPerformed(evt);
            }
        });
        cbbNCC.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbbNCCPropertyChange(evt);
            }
        });

        lblSDTNCC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSDTNCC.setText("SĐT");

        lblDiaChiNCC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDiaChiNCC.setText("Địa chỉ");

        lblTenHD.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTenHD.setText("Mã HĐ");

        txtMaHD.setEditable(false);
        txtMaHD.setForeground(new java.awt.Color(0, 0, 153));
        txtMaHD.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMaHD.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtMaHD.sets_placeholder("");
        txtMaHD.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtMaHD.sets_placeholderForeGround(new java.awt.Color(204, 0, 204));

        txtSDT.setEditable(false);
        txtSDT.setForeground(new java.awt.Color(0, 0, 153));
        txtSDT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSDT.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtSDT.sets_placeholder("................");
        txtSDT.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtSDT.sets_placeholderForeGround(new java.awt.Color(204, 0, 204));

        txtDiaChi.setEditable(false);
        txtDiaChi.setForeground(new java.awt.Color(0, 0, 153));
        txtDiaChi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDiaChi.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtDiaChi.sets_placeholder("................");
        txtDiaChi.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtDiaChi.sets_placeholderForeGround(new java.awt.Color(204, 0, 204));

        txtTenNV.setEditable(false);
        txtTenNV.setForeground(new java.awt.Color(0, 0, 153));
        txtTenNV.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTenNV.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtTenNV.sets_placeholder("");
        txtTenNV.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtTenNV.sets_placeholderForeGround(new java.awt.Color(204, 0, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNhaCungCap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNgayTaoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSDTNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_Date, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(cbbNCC, 0, 200, Short.MAX_VALUE))
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblNguoiTaoHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDiaChiNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTenHD, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 2, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNgayTaoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSDTNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNguoiTaoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTenHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDiaChiNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1194, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public static double SoLuongMua;
    public static String GhiChu;
    public static boolean Huy;
    
    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
       if (evt.getClickCount() >= 2) {
            jdlThongTinSanPham jdl = new jdlThongTinSanPham((JFrame) SwingUtilities.getWindowAncestor(this), true);
            jdl.setVisible(true);
            if (Huy) {
                return;
            }
            // Lấy IDSanPham <=> Lấy sản phẩm theo ID

            String MaSP = tblSanPham.getValueAt(tblSanPham.getSelectedRow(), 0).toString();
            String TenSP = tblSanPham.getValueAt(tblSanPham.getSelectedRow(), 1).toString();
            double DonGia = Double.parseDouble(tblSanPham.getValueAt(tblSanPham.getSelectedRow(), 3).toString());
            double ThanhTien = DonGia * SoLuongMua;
            
            ThemSPVaotblCTHD(MaSP, TenSP, SoLuongMua, DonGia, ThanhTien, GhiChu);

            txtTongTien.setText(ChuyenDoi.DinhDangTien(TinhTien()));
        }
    }//GEN-LAST:event_tblSanPhamMouseClicked
    
    private void ThemSPVaotblCTHD(String MaSP, String TenSP, double SoLuong, double DonGia, double ThanhTien, String GhiChu) {
        DefaultTableModel tblModel = (DefaultTableModel) tblCHHD.getModel();

        Object ojb[] = new Object[7];
        ojb[0] = tblModel.getRowCount() + 1;
        ojb[1] = MaSP;
        ojb[2] = TenSP;
        ojb[3] = SoLuong;
        ojb[4] = ChuyenDoi.DinhDangTien(DonGia);
        ojb[5] = ChuyenDoi.DinhDangTien(ThanhTien);
        ojb[6] = GhiChu;

        tblModel.addRow(ojb);
    }
    
    private double TinhTien() {
        double tongTien = 0;
        for (int i = 0; i < tblCHHD.getRowCount(); i++) {
            tongTien += ChuyenDoi.ChuyenTien(tblCHHD.getValueAt(i, 5).toString());
        }

        return tongTien;
    }
    
    private void cbbChonLoaiSPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbChonLoaiSPItemStateChanged
        if (cbbChonLoaiSP.getSelectedIndex() > 0) {
            String tenLoaiSP = cbbChonLoaiSP.getSelectedItem().toString();           
            String maLoaiSP = BLLLoaiSP.GetMaLSPByTenLSP(tenLoaiSP);
            
            String keyWord = txtTuKhoaSanPham.getText();
            if (keyWord.isEmpty()) {
                BLLSanPham.LocDSSPTheoMaLoaiSP(tblSanPham, maLoaiSP);
            }else{
                BLLSanPham.LocDSSP(tblSanPham, keyWord, maLoaiSP);
            }
        }else{
            BLLSanPham.LoadSanPhamHoaDon(tblSanPham);
        }
    }//GEN-LAST:event_cbbChonLoaiSPItemStateChanged

    private void cbbChonLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbChonLoaiSPActionPerformed
        
    }//GEN-LAST:event_cbbChonLoaiSPActionPerformed

    private void cbbNCCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbNCCItemStateChanged
        if (cbbNCC.getItemCount() > 0) {
            String cbb = cbbNCC.getSelectedItem().toString();
            NhaCC ncc = BLLNhaCC.LayNCCTheoTen(cbb);
            if (ncc != null) {
                txtDiaChi.setText(ncc.getDiaChi());
                txtSDT.setText(ncc.getSDT());
            }
        }
    }//GEN-LAST:event_cbbNCCItemStateChanged

    private void cbbNCCMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbNCCMouseReleased

    }//GEN-LAST:event_cbbNCCMouseReleased

    private void cbbNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNCCActionPerformed

    }//GEN-LAST:event_cbbNCCActionPerformed

    private void cbbNCCPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbbNCCPropertyChange

    }//GEN-LAST:event_cbbNCCPropertyChange
    public void XuatHoaDon(String Ma_HD_Nhap) {
        try {

            Hashtable map = new Hashtable();
            JasperReport report = JasperCompileManager.compileReport("src/Du_An_DESIGN/rptHoaDonNhap.jrxml");

            map.put("Ma_HD_Nhap", Ma_HD_Nhap);

            JasperPrint p = JasperFillManager.fillReport(report, map, SQLHelper.Connection);
            JasperViewer.viewReport(p, false);
            JasperExportManager.exportReportToPdfFile(p, "test.pdf");
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }
    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        if (tblCHHD.getRowCount() <= 0) {
            ThongBao.ThongBaoDangNhap("Thông báo", "Chưa chọn sản phẩm");
            return;
        }

        

        if (cbbNCC.getSelectedIndex() <= 0) {
            ThongBao.ThongBaoDangNhap("Thông báo", "Chưa chọn Nhà cung cấp");
            return;
        }
        
        String tenNV = txtTenNV.getText();
        NhanVien nv = BLLNhanVien.LayNVTheoTen(tenNV);
        String maNV = nv.getMaNV();
        
        String tenNCC = cbbNCC.getSelectedItem().toString();
        NhaCC ncc = BLLNhaCC.LayNCCTheoTen(tenNCC);
        String maNCC = ncc.getMaNCC();
        
        String maHD = txtMaHD.getText();
        
        HDNhap hdNhap = new HDNhap();
        hdNhap.setMa_HD_Nhap(maHD);
        hdNhap.setNgayTao(txt_Date.getDate());
        hdNhap.setMaNV(maNV);
        hdNhap.setMaNCC(maNCC);
        hdNhap.setTongTien(ChuyenDoi.LaySoDouble(txtTongTien.getText()));
        hdNhap.setGhiChu(txtTTGhiChu.getText());
        
        DALHDNhap.ThemHDNhap(hdNhap);
        
        
        BLLCTHDNhap.ThemCTHDNhap(tblCHHD, maHD);
        
        hdNhap.setMa_HD_Nhap(BLLHoaDonNhap.GetTenHDBySoHoaDon(hdNhap.getMa_HD_Nhap()));
        //System.out.println(hdXuat.getMa_HD_Xuat());
        
        XuatHoaDon(hdNhap.getMa_HD_Nhap());
        
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnNewHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewHDActionPerformed
        cbbNCC.setSelectedIndex(0);
        txtDiaChi.setText("");
        txtSDT.setText("");
        txtTTGhiChu.setText("");
        txtMaHD.setText(BLLHoaDonNhap.TaoMaHDN());
        txtTongTien.setText("");
        
        DefaultTableModel tbl = (DefaultTableModel) tblCHHD.getModel();
        for (int i = tbl.getRowCount() - 1; i >= 0; i--) {
            tbl.removeRow(i);
        }
    }//GEN-LAST:event_btnNewHDActionPerformed

    private void txtTuKhoaSanPhamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTuKhoaSanPhamKeyReleased
        String keyWord = txtTuKhoaSanPham.getText();
        
        if (cbbChonLoaiSP.getSelectedIndex() > 0) {
            String tenLoaiSP = cbbChonLoaiSP.getSelectedItem().toString();           
            String maLoaiSP = BLLLoaiSP.GetMaLSPByTenLSP(tenLoaiSP);
                                  
            BLLSanPham.LocDSSP(tblSanPham, keyWord, maLoaiSP);
        }else{
            BLLSanPham.LocDSSPTheoKeyWord(tblSanPham, keyWord);
        }
    }//GEN-LAST:event_txtTuKhoaSanPhamKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.shady.scontrols.SButton btnNewHD;
    private com.shady.scontrols.SButton btnThanhToan;
    private javax.swing.JComboBox<String> cbbChonLoaiSP;
    private javax.swing.JComboBox<String> cbbNCC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblChonLoaiSP;
    private javax.swing.JLabel lblDiaChiNCC;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblNgayTaoHD;
    private javax.swing.JLabel lblNguoiTaoHD;
    private javax.swing.JLabel lblNhaCungCap;
    private javax.swing.JLabel lblSDTNCC;
    private javax.swing.JLabel lblTenHD;
    private javax.swing.JLabel lblTimKiemSP;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JTable tblCHHD;
    private javax.swing.JTable tblSanPham;
    private com.shady.scontrols.STextField txtDiaChi;
    private com.shady.scontrols.STextField txtMaHD;
    private com.shady.scontrols.STextField txtSDT;
    private com.shady.scontrols.STextField txtTTGhiChu;
    private com.shady.scontrols.STextField txtTenNV;
    private com.shady.scontrols.STextField txtTongTien;
    private com.shady.scontrols.STextField txtTuKhoaSanPham;
    private com.toedter.calendar.JDateChooser txt_Date;
    // End of variables declaration//GEN-END:variables
}
