/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Du_An_DESIGN;
import Du_An_BLL.BLLKhachHang;
import Du_An_DTO.KhachHang;
import Du_An_HELPER.HoTroNhapSo;
import Du_An_HELPER.ThongBao;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class TabKhachHang extends javax.swing.JPanel {

    /**
     * Creates new form TabKhachHang
     */
    public TabKhachHang() {
        initComponents();
        
        BLLKhachHang.LoadKhachHang(tblDanhSach);
        lblvTenKH.setVisible(false);
        lblvSDT.setVisible(false);
        lblvDC.setVisible(false);
        lblvDC1.setVisible(false);
        lblvEmail.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        lblTenKhachHang = new javax.swing.JLabel();
        lblMaKhachHang = new javax.swing.JLabel();
        txtMaKhachHang = new com.shady.scontrols.STextField();
        txtTenKhachHang = new com.shady.scontrols.STextField();
        lblSĐT = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtSoDienThoai = new com.shady.scontrols.STextField();
        txtDiaChi = new com.shady.scontrols.STextField();
        txtEmail = new com.shady.scontrols.STextField();
        lblGhiChu = new javax.swing.JLabel();
        SbtnThem = new com.shady.scontrols.SButton();
        SbtnSua = new com.shady.scontrols.SButton();
        SbtnXoa = new com.shady.scontrols.SButton();
        SbtnLamMoi = new com.shady.scontrols.SButton();
        txtTimKiem = new com.shady.scontrols.STextField();
        txtGhiChu = new com.shady.scontrols.STextField();
        lblvTenKH = new javax.swing.JLabel();
        lblvDC = new javax.swing.JLabel();
        lblvSDT = new javax.swing.JLabel();
        lblvEmail = new javax.swing.JLabel();
        lblGhiChu1 = new javax.swing.JLabel();
        lblvDC1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new com.shady.scontrols.STable();

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(203, 224, 255));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setOpaque(false);

        lblTenKhachHang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTenKhachHang.setForeground(new java.awt.Color(0, 0, 153));
        lblTenKhachHang.setText("Tên Khách Hàng");

        lblMaKhachHang.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMaKhachHang.setForeground(new java.awt.Color(0, 0, 153));
        lblMaKhachHang.setText("Mã Khách Hàng");

        txtMaKhachHang.setForeground(new java.awt.Color(0, 0, 153));
        txtMaKhachHang.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtMaKhachHang.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtMaKhachHang.sets_errorBackground(new java.awt.Color(255, 255, 255));
        txtMaKhachHang.sets_errorBorder(new java.awt.Color(255, 255, 255));
        txtMaKhachHang.sets_placeholder("Mời Bạn Nhập");
        txtMaKhachHang.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtMaKhachHang.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));

        txtTenKhachHang.setForeground(new java.awt.Color(0, 0, 153));
        txtTenKhachHang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTenKhachHang.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtTenKhachHang.sets_placeholder("Mời Bạn Nhập");
        txtTenKhachHang.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtTenKhachHang.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtTenKhachHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenKhachHangKeyReleased(evt);
            }
        });

        lblSĐT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSĐT.setForeground(new java.awt.Color(0, 0, 153));
        lblSĐT.setText("Số Điện Thoai");

        lblDiaChi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDiaChi.setForeground(new java.awt.Color(0, 0, 153));
        lblDiaChi.setText("Địa Chỉ");

        lblEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 0, 153));
        lblEmail.setText("Email");

        txtSoDienThoai.setForeground(new java.awt.Color(0, 0, 153));
        txtSoDienThoai.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSoDienThoai.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtSoDienThoai.sets_placeholder("Mời Bạn Nhập");
        txtSoDienThoai.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtSoDienThoai.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtSoDienThoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoDienThoaiKeyReleased(evt);
            }
        });

        txtDiaChi.setForeground(new java.awt.Color(0, 0, 153));
        txtDiaChi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDiaChi.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtDiaChi.sets_placeholder("Mời Bạn Nhập");
        txtDiaChi.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtDiaChi.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtDiaChi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiaChiKeyReleased(evt);
            }
        });

        txtEmail.setForeground(new java.awt.Color(0, 0, 153));
        txtEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEmail.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtEmail.sets_placeholder("Mời Bạn Nhập");
        txtEmail.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtEmail.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        lblGhiChu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGhiChu.setForeground(new java.awt.Color(0, 0, 153));
        lblGhiChu.setText("Tìm Kiếm");

        SbtnThem.setForeground(new java.awt.Color(0, 0, 153));
        SbtnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/click.png"))); // NOI18N
        SbtnThem.setText("Thêm ");
        SbtnThem.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SbtnThem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SbtnThem.setIconTextGap(20);
        SbtnThem.setMargin(new java.awt.Insets(5, 14, 5, 14));
        SbtnThem.setMaximumSize(new java.awt.Dimension(70, 30));
        SbtnThem.sets_borderColor(new java.awt.Color(153, 0, 153));
        SbtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnThemActionPerformed(evt);
            }
        });

        SbtnSua.setForeground(new java.awt.Color(0, 0, 153));
        SbtnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/click.png"))); // NOI18N
        SbtnSua.setText("Sửa");
        SbtnSua.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SbtnSua.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SbtnSua.setIconTextGap(20);
        SbtnSua.setMargin(new java.awt.Insets(5, 14, 5, 14));
        SbtnSua.setMaximumSize(new java.awt.Dimension(70, 30));
        SbtnSua.sets_borderColor(new java.awt.Color(153, 0, 153));
        SbtnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnSuaActionPerformed(evt);
            }
        });

        SbtnXoa.setForeground(new java.awt.Color(0, 0, 153));
        SbtnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/click.png"))); // NOI18N
        SbtnXoa.setText("Xoá");
        SbtnXoa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SbtnXoa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SbtnXoa.setIconTextGap(20);
        SbtnXoa.setMargin(new java.awt.Insets(5, 14, 5, 14));
        SbtnXoa.setMaximumSize(new java.awt.Dimension(70, 30));
        SbtnXoa.sets_borderColor(new java.awt.Color(153, 0, 153));
        SbtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnXoaActionPerformed(evt);
            }
        });

        SbtnLamMoi.setForeground(new java.awt.Color(0, 0, 153));
        SbtnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/click.png"))); // NOI18N
        SbtnLamMoi.setText("Làm Mới");
        SbtnLamMoi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SbtnLamMoi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SbtnLamMoi.setIconTextGap(10);
        SbtnLamMoi.setMargin(new java.awt.Insets(5, 14, 5, 14));
        SbtnLamMoi.setMaximumSize(new java.awt.Dimension(70, 30));
        SbtnLamMoi.sets_borderColor(new java.awt.Color(153, 0, 153));
        SbtnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnLamMoiActionPerformed(evt);
            }
        });

        txtTimKiem.setForeground(new java.awt.Color(0, 0, 153));
        txtTimKiem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTimKiem.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtTimKiem.sets_placeholder("Mời Bạn Nhập Từ Khoá Cần Tìm");
        txtTimKiem.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtTimKiem.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        txtGhiChu.setForeground(new java.awt.Color(0, 0, 153));
        txtGhiChu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtGhiChu.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtGhiChu.sets_placeholder("Ghi Chú");
        txtGhiChu.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtGhiChu.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));

        lblvTenKH.setForeground(new java.awt.Color(255, 0, 51));
        lblvTenKH.setText("jLabel2");

        lblvDC.setForeground(new java.awt.Color(255, 0, 51));
        lblvDC.setText("jLabel3");

        lblvSDT.setForeground(new java.awt.Color(255, 0, 51));
        lblvSDT.setText("jLabel4");

        lblvEmail.setForeground(new java.awt.Color(255, 0, 51));
        lblvEmail.setText("jLabel5");

        lblGhiChu1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGhiChu1.setForeground(new java.awt.Color(0, 0, 153));
        lblGhiChu1.setText("Ghi Chú");

        lblvDC1.setForeground(new java.awt.Color(255, 0, 51));
        lblvDC1.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblGhiChu1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGhiChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(25, 25, 25))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(15, 15, 15)
                                    .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblvDC1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblvTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(40, 40, 40)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(15, 15, 15)
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblSĐT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(15, 15, 15)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblvDC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblvSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(10, 10, 10))))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SbtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SbtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblvEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SbtnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(SbtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblvDC1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSĐT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SbtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SbtnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblvSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblvTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SbtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGhiChu1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblvDC, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblvEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SbtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tblDanhSach.setBackground(new java.awt.Color(203, 224, 255));
        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Khách Hàng", "Tên Khách Hàng", "Địa Chỉ", "Số Điện Thoại", "Email", "Ghi Chú"
            }
        ));
        tblDanhSach.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSach);
        if (tblDanhSach.getColumnModel().getColumnCount() > 0) {
            tblDanhSach.getColumnModel().getColumn(1).setMinWidth(0);
            tblDanhSach.getColumnModel().getColumn(1).setMaxWidth(0);
        }

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1)
                .addGap(20, 20, 20))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        int dongDuocChon = tblDanhSach.getSelectedRow();
        String MaKH = tblDanhSach.getValueAt(dongDuocChon, 1).toString();
        KhachHang KH = BLLKhachHang.LayKHTheoMa(MaKH);
        txtMaKhachHang.setText(KH.getMaKhachHang());
        txtTenKhachHang.setText(KH.getTenKhachHang());
        txtDiaChi.setText(KH.getDiaChi());
        txtSoDienThoai.setText(KH.getSDT());
        txtEmail.setText(KH.getEmail());
        txtGhiChu.setText(KH.getGhiChu());
        txtMaKhachHang.setEnabled(false);
    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void SbtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnThemActionPerformed
        
        txtMaKhachHang.setText(BLLKhachHang.TaoMaKH());
        String MaKH = txtMaKhachHang.getText();
        String TenKhachHang = txtTenKhachHang.getText();
        String DiaChi = txtDiaChi.getText();
        String SDT = txtSoDienThoai.getText();
        String Email = txtEmail.getText();
        String GhiChu = txtGhiChu.getText();
        if(this.txtTenKhachHang.getText().length() == 0 || this.txtDiaChi.getText().length() == 0
                || this.txtSoDienThoai.getText().length() == 0 || this.txtEmail.getText().length() == 0 ) {
        if (this.txtTenKhachHang.getText().length() == 0) {
 
            lblvTenKH.setVisible(true);
            lblvTenKH.setText("Họ và tên không được bỏ trống");
        } 
        if (this.txtDiaChi.getText().length() == 0) {
            
            lblvDC.setVisible(true);
            lblvDC.setText("Địa chỉ không được bỏ trống");
        } 
        if (this.txtSoDienThoai.getText().length() == 0) {
            
            lblvSDT.setVisible(true);
            lblvSDT.setText("Số điện thoại không được bỏ trống");
        } 
        if (this.txtEmail.getText().length() == 0) {
            
            lblvEmail.setVisible(true);
            lblvEmail.setText("Email không được bỏ trống");
        } 
        }else {
            KhachHang KH= new KhachHang(MaKH, TenKhachHang, DiaChi, SDT, Email, GhiChu);
            //ThongBao.ThongBaoDangNhap("Thông Báo", " Mã Khách Hàng " + MaKhachHang + " Được Thêm Thành Công");
            BLLKhachHang.ThemKhachHang(KH);
            ThongBao.ThongBaoSQL("Thông Báo", " Thêm Thành công");
            BLLKhachHang.LoadKhachHang(tblDanhSach);
        }
    }//GEN-LAST:event_SbtnThemActionPerformed

    private void SbtnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnSuaActionPerformed
        String MaKhachHang = txtMaKhachHang.getText();
        String TenKhachHang = txtTenKhachHang.getText();
        String DiaChi = txtDiaChi.getText();
        String SDT = txtSoDienThoai.getText();
        String Email = txtEmail.getText();
        String GhiChu = txtGhiChu.getText();
        
        KhachHang KH = new KhachHang(MaKhachHang, TenKhachHang, DiaChi, SDT, Email, GhiChu);
        BLLKhachHang.UpdateKhachHang(KH);
        ThongBao.ThongBaoDangNhap("Thông Báo", " Mã Khách Hàng " + MaKhachHang + " Được Sửa Thành Công");
        
        BLLKhachHang.LoadKhachHang(tblDanhSach);
    }//GEN-LAST:event_SbtnSuaActionPerformed

    private void SbtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnXoaActionPerformed
        if (this.txtMaKhachHang.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", " Bạn Chưa Chọn Dòng Để Xoá !!");

        } else {

            int DSViTri[] = tblDanhSach.getSelectedRows();
            List<String> lstMaKH = new ArrayList<>();

            for (int i : DSViTri) {
                String MaKH = tblDanhSach.getValueAt(i, 1).toString();
                lstMaKH.add(MaKH);
            }

            BLLKhachHang.Delete(lstMaKH);
            ThongBao.ThongBaoSQL("Thông Báo", " Xoá Thành Công !!");
            BLLKhachHang.LoadKhachHang(tblDanhSach);
        }
    }//GEN-LAST:event_SbtnXoaActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        String TenNhanVien = "%" + txtTimKiem.getText() + "%";
        String SDT =  txtTimKiem.getText() + "%";
       
        BLLKhachHang.TimKhachHang(tblDanhSach, TenNhanVien, SDT);
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void txtSoDienThoaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoDienThoaiKeyReleased
        // TODO add your handling code here:
        HoTroNhapSo.luonNhapSo(evt);
         lblvSDT.setVisible(false);
    }//GEN-LAST:event_txtSoDienThoaiKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
       String Email_Pattern = "^[a-zA-Z0-9]{0,30}[@][a-zA-z0-9]{0,10}[.][a-zA-Z]{2,5}$";
        Pattern pattern = Pattern.compile(Email_Pattern);
        Matcher matcher = pattern.matcher(txtEmail.getText());
        if (!matcher.matches()) {
            lblvEmail.setText("Email không đúng định Dạng");
        } else {
            lblvEmail.setVisible(false);
        }
        
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtTenKhachHangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenKhachHangKeyReleased
        lblvTenKH.setVisible(false);
    }//GEN-LAST:event_txtTenKhachHangKeyReleased

    private void txtDiaChiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaChiKeyReleased
        // TODO add your handling code here:
         lblvDC.setVisible(false);
    }//GEN-LAST:event_txtDiaChiKeyReleased

    private void SbtnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnLamMoiActionPerformed
        // TODO add your handling code here:
        txtDiaChi.setText("");
        txtEmail.setText("");
        txtGhiChu.setText("");
        txtMaKhachHang.setText("");
        txtSoDienThoai.setText("");
        txtTenKhachHang.setText("");
        txtTimKiem.setText("");
        
        lblvTenKH.setVisible(false);
        lblvSDT.setVisible(false);
        lblvDC.setVisible(false);
        lblvEmail.setVisible(false);
    }//GEN-LAST:event_SbtnLamMoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.shady.scontrols.SButton SbtnLamMoi;
    private com.shady.scontrols.SButton SbtnSua;
    private com.shady.scontrols.SButton SbtnThem;
    private com.shady.scontrols.SButton SbtnXoa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblGhiChu1;
    private javax.swing.JLabel lblMaKhachHang;
    private javax.swing.JLabel lblSĐT;
    private javax.swing.JLabel lblTenKhachHang;
    private javax.swing.JLabel lblvDC;
    private javax.swing.JLabel lblvDC1;
    private javax.swing.JLabel lblvEmail;
    private javax.swing.JLabel lblvSDT;
    private javax.swing.JLabel lblvTenKH;
    private com.shady.scontrols.STable tblDanhSach;
    private com.shady.scontrols.STextField txtDiaChi;
    private com.shady.scontrols.STextField txtEmail;
    private com.shady.scontrols.STextField txtGhiChu;
    private com.shady.scontrols.STextField txtMaKhachHang;
    private com.shady.scontrols.STextField txtSoDienThoai;
    private com.shady.scontrols.STextField txtTenKhachHang;
    private com.shady.scontrols.STextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
