/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Du_An_DESIGN;

import Du_An_BLL.BLLNhaCC;
import Du_An_DTO.NhaCC;
import Du_An_HELPER.HoTroNhapSo;
import Du_An_HELPER.ThongBao;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author LENOVO
 */
public class TabNhaCungCap extends javax.swing.JPanel {

    /**
     * Creates new form TabNhaCungCap
     */
    public TabNhaCungCap() {
        initComponents();
        BLLNhaCC.LoadNCC(tblDanhSach);
        lblvTenNCC.setVisible(false);
        lblvSDT.setVisible(false);
        lblvDC.setVisible(false);
        lblvEmail.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        lblTenNhaCC = new javax.swing.JLabel();
        lblNhaCC = new javax.swing.JLabel();
        txtMaNhaCC = new com.shady.scontrols.STextField();
        txtTenNhaCC = new com.shady.scontrols.STextField();
        lblSĐT = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtDiaChi = new com.shady.scontrols.STextField();
        txtEmail = new com.shady.scontrols.STextField();
        lblGhiChu = new javax.swing.JLabel();
        SbtnThem = new com.shady.scontrols.SButton();
        SbtnSua = new com.shady.scontrols.SButton();
        SbtnXoa = new com.shady.scontrols.SButton();
        SbtnLamMoi = new com.shady.scontrols.SButton();
        txtTimKiem = new com.shady.scontrols.STextField();
        txtGhiChu = new com.shady.scontrols.STextField();
        lblTimKiem = new javax.swing.JLabel();
        lblvTenNCC = new javax.swing.JLabel();
        lblvSDT = new javax.swing.JLabel();
        lblvDC = new javax.swing.JLabel();
        txtSĐT = new com.shady.scontrols.STextField();
        lblvEmail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new com.shady.scontrols.STable();

        kGradientPanel1.setkEndColor(new java.awt.Color(203, 224, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setOpaque(false);

        lblTenNhaCC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTenNhaCC.setForeground(new java.awt.Color(0, 0, 153));
        lblTenNhaCC.setText("Tên Nhà CC");

        lblNhaCC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNhaCC.setForeground(new java.awt.Color(0, 0, 153));
        lblNhaCC.setText("Mã Nhà CC");

        txtMaNhaCC.setForeground(new java.awt.Color(0, 0, 153));
        txtMaNhaCC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtMaNhaCC.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtMaNhaCC.sets_errorBackground(new java.awt.Color(255, 255, 255));
        txtMaNhaCC.sets_errorBorder(new java.awt.Color(255, 255, 255));
        txtMaNhaCC.sets_placeholder("Mời Bạn Nhập");
        txtMaNhaCC.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtMaNhaCC.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));

        txtTenNhaCC.setForeground(new java.awt.Color(0, 0, 153));
        txtTenNhaCC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTenNhaCC.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtTenNhaCC.sets_placeholder("Mời Bạn Nhập");
        txtTenNhaCC.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtTenNhaCC.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtTenNhaCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNhaCCActionPerformed(evt);
            }
        });
        txtTenNhaCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenNhaCCKeyReleased(evt);
            }
        });

        lblSĐT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSĐT.setForeground(new java.awt.Color(0, 0, 153));
        lblSĐT.setText("Số Điện Thoai");

        lblDiaChi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDiaChi.setForeground(new java.awt.Color(0, 0, 153));
        lblDiaChi.setText("Địa Chỉ");

        lblEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 0, 153));
        lblEmail.setText("Email");

        txtDiaChi.setForeground(new java.awt.Color(0, 0, 153));
        txtDiaChi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDiaChi.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtDiaChi.sets_placeholder("Mời Bạn Nhập");
        txtDiaChi.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtDiaChi.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });
        txtDiaChi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiaChiKeyReleased(evt);
            }
        });

        txtEmail.setForeground(new java.awt.Color(0, 0, 153));
        txtEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEmail.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtEmail.sets_placeholder("Mời Bạn Nhập");
        txtEmail.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtEmail.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        lblGhiChu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGhiChu.setForeground(new java.awt.Color(0, 0, 153));
        lblGhiChu.setText("Ghi Chú");

        SbtnThem.setForeground(new java.awt.Color(0, 0, 153));
        SbtnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/click.png"))); // NOI18N
        SbtnThem.setText("Thêm ");
        SbtnThem.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SbtnThem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SbtnThem.setIconTextGap(20);
        SbtnThem.setMargin(new java.awt.Insets(5, 14, 5, 14));
        SbtnThem.setMaximumSize(new java.awt.Dimension(70, 30));
        SbtnThem.sets_borderColor(new java.awt.Color(153, 0, 153));
        SbtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnThemActionPerformed(evt);
            }
        });

        SbtnSua.setForeground(new java.awt.Color(0, 0, 153));
        SbtnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/click.png"))); // NOI18N
        SbtnSua.setText("Sửa");
        SbtnSua.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SbtnSua.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SbtnSua.setIconTextGap(20);
        SbtnSua.setMargin(new java.awt.Insets(5, 14, 5, 14));
        SbtnSua.setMaximumSize(new java.awt.Dimension(70, 30));
        SbtnSua.sets_borderColor(new java.awt.Color(153, 0, 153));
        SbtnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnSuaActionPerformed(evt);
            }
        });

        SbtnXoa.setForeground(new java.awt.Color(0, 0, 153));
        SbtnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/click.png"))); // NOI18N
        SbtnXoa.setText("Xoá");
        SbtnXoa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SbtnXoa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SbtnXoa.setIconTextGap(20);
        SbtnXoa.setMargin(new java.awt.Insets(5, 14, 5, 14));
        SbtnXoa.setMaximumSize(new java.awt.Dimension(70, 30));
        SbtnXoa.sets_borderColor(new java.awt.Color(153, 0, 153));
        SbtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnXoaActionPerformed(evt);
            }
        });

        SbtnLamMoi.setForeground(new java.awt.Color(0, 0, 153));
        SbtnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/click.png"))); // NOI18N
        SbtnLamMoi.setText("Làm Mới");
        SbtnLamMoi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SbtnLamMoi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SbtnLamMoi.setIconTextGap(10);
        SbtnLamMoi.setMargin(new java.awt.Insets(5, 14, 5, 14));
        SbtnLamMoi.setMaximumSize(new java.awt.Dimension(70, 30));
        SbtnLamMoi.sets_borderColor(new java.awt.Color(153, 0, 153));
        SbtnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnLamMoiActionPerformed(evt);
            }
        });

        txtTimKiem.setForeground(new java.awt.Color(0, 0, 153));
        txtTimKiem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTimKiem.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtTimKiem.sets_placeholder("Mời Bạn Nhập Từ Khoá Cần Tìm");
        txtTimKiem.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtTimKiem.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        txtGhiChu.setForeground(new java.awt.Color(0, 0, 153));
        txtGhiChu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtGhiChu.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtGhiChu.sets_placeholder("Ghi Chú");
        txtGhiChu.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtGhiChu.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));

        lblTimKiem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTimKiem.setForeground(new java.awt.Color(0, 0, 153));
        lblTimKiem.setText("Tìm Kiếm");

        lblvTenNCC.setForeground(new java.awt.Color(255, 0, 51));
        lblvTenNCC.setText("jLabel1");

        lblvSDT.setForeground(new java.awt.Color(255, 0, 51));
        lblvSDT.setText("jLabel2");

        lblvDC.setForeground(new java.awt.Color(255, 0, 51));
        lblvDC.setText("jLabel3");

        txtSĐT.setForeground(new java.awt.Color(0, 0, 153));
        txtSĐT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSĐT.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtSĐT.sets_placeholder("Mời Bạn Nhập");
        txtSĐT.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtSĐT.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtSĐT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSĐTKeyReleased(evt);
            }
        });

        lblvEmail.setForeground(new java.awt.Color(255, 0, 51));
        lblvEmail.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(txtMaNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTenNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblvTenNCC))
                                    .addComponent(txtTenNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblvDC))
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSĐT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(lblvSDT))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSĐT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtGhiChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(339, 339, 339))
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(3, 3, 3)))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SbtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SbtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SbtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SbtnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblvEmail)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblvEmail))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMaNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSĐT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSĐT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblvSDT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTenNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTenNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SbtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SbtnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblvTenNCC)
                            .addComponent(lblvDC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SbtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SbtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tblDanhSach.setBackground(new java.awt.Color(203, 224, 255));
        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Nhà CC", "Tên Nhà CC", "Số Điện Thoại", "Địa Chỉ", "Email", "Ghi Chú"
            }
        ));
        tblDanhSach.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSach);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1)
                .addGap(20, 20, 20))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1110, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        int dongDuocChon = tblDanhSach.getSelectedRow();
        String MaNCC = tblDanhSach.getValueAt(dongDuocChon, 1).toString();
        NhaCC ncc = BLLNhaCC.LayNCCTheoMa(MaNCC);
        txtMaNhaCC.setText(ncc.getMaNCC() + "");
        txtTenNhaCC.setText(ncc.getTenNCC());
        txtSĐT.setText(ncc.getSDT());
        txtDiaChi.setText(ncc.getDiaChi());
        txtEmail.setText(ncc.getEmail());
        txtGhiChu.setText(ncc.getGhiChu());
    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void SbtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnThemActionPerformed
        txtMaNhaCC.setText(BLLNhaCC.TaoMaNCC());
        String MaNCC = txtMaNhaCC.getText();
        String TenNCC = txtTenNhaCC.getText();
        String SDT = txtSĐT.getText();
        String DiaChi = txtDiaChi.getText();
        String Email = txtEmail.getText();
        String GhiChu = txtGhiChu.getText();
        
        if(this.txtTenNhaCC.getText().length() == 0 || this.txtSĐT.getText().length() == 0 ||
            this.txtDiaChi.getText().length() == 0 || this.txtEmail.getText().length() == 0 ) {
        if (this.txtTenNhaCC.getText().length() == 0) {
            
            lblvTenNCC.setVisible(true);
            lblvTenNCC.setText("Tên nhà cung cấp không được bỏ trống");
        } 
        if (this.txtSĐT.getText().length() == 0) {
            
            lblvSDT.setVisible(true);
            lblvSDT.setText("Số điện thoại không được bỏ trống");
        } 
        if (this.txtDiaChi.getText().length() == 0) {
            
            lblvDC.setVisible(true);
            lblvDC.setText("Địa chỉ không được bỏ trống");
        }  
        if (this.txtEmail.getText().length() == 0) {
            
            lblvEmail.setVisible(true);
            lblvEmail.setText("Email không được bỏ trống");
        } 
        }else {
            NhaCC ncc = new NhaCC(MaNCC, TenNCC, SDT, DiaChi, Email, GhiChu);
            BLLNhaCC.ThemNhaCC(ncc);
            BLLNhaCC.LoadNCC(tblDanhSach);
            ThongBao.ThongBaoSQL("Thông Báo", "Thêm thành công.");
        }
    }//GEN-LAST:event_SbtnThemActionPerformed

    private void SbtnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnSuaActionPerformed
        String MaNCC = txtMaNhaCC.getText();
        String TenNCC = txtTenNhaCC.getText();
        String SDT = txtSĐT.getText();
        String DiaChi = txtDiaChi.getText();
        String Email = txtEmail.getText();
        String GhiChu = txtGhiChu.getText();
        if (this.txtTenNhaCC.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Mã Nhân Viên Không Được Bỏ Trống");
        } else if (this.txtSĐT.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Họ Và Tên Không Được Bỏ Trống");
        } else if (this.txtDiaChi.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Địa Chỉ Không Được Bỏ Trống");
        } else if (this.txtEmail.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Email Không Được Bỏ Trống");
        } else {
            NhaCC ncc = new NhaCC(MaNCC, TenNCC, SDT, DiaChi, Email, GhiChu);
            BLLNhaCC.UpdateNhaCC(ncc);
            BLLNhaCC.LoadNCC(tblDanhSach);
            ThongBao.ThongBaoSQL("Thông Báo", "Sửa thành công.");
        }
    }//GEN-LAST:event_SbtnSuaActionPerformed

    private void SbtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnXoaActionPerformed
        if (this.txtMaNhaCC.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", " Bạn Chưa Chọn Dòng Để Xoá !!");

        } else {

            int DSViTri[] = tblDanhSach.getSelectedRows();
            List<String> lstMaSP = new ArrayList<>();

            for (int i : DSViTri) {
                String MaNV = tblDanhSach.getValueAt(i, 1).toString();
                lstMaSP.add(MaNV);
            }

            BLLNhaCC.Delete(lstMaSP);

            BLLNhaCC.LoadNCC(tblDanhSach);
        }
    }//GEN-LAST:event_SbtnXoaActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        String TenNhaCC = "%" + txtTimKiem.getText() + "%";
        BLLNhaCC.TimNhaCC(tblDanhSach, TenNhaCC);
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        String Email_Pattern = "^[a-zA-Z0-9]{0,30}[@][a-zA-z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern pattern = Pattern.compile(Email_Pattern);
        Matcher matcher = pattern.matcher(txtEmail.getText());
        if (!matcher.matches()) {
            lblvEmail.setText("Email không đúng định Dạng");
        } else {
            lblvEmail.setVisible(false);
        }
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtTenNhaCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNhaCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNhaCCActionPerformed

    private void txtTenNhaCCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenNhaCCKeyReleased
        // TODO add your handling code here:
        lblvTenNCC.setVisible(false);
    }//GEN-LAST:event_txtTenNhaCCKeyReleased

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void txtDiaChiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaChiKeyReleased
        lblvDC.setVisible(false);
    }//GEN-LAST:event_txtDiaChiKeyReleased

    private void SbtnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnLamMoiActionPerformed
        // TODO add your handling code here:
        txtDiaChi.setText("");
        txtEmail.setText("");
        txtGhiChu.setText("");
        txtMaNhaCC.setText("");
        txtSĐT.setText("");
        txtTenNhaCC.setText("");
        txtTimKiem.setText("");
        
        lblvTenNCC.setVisible(false);
        lblvSDT.setVisible(false);
        lblvDC.setVisible(false);
        lblvEmail.setVisible(false);
    }//GEN-LAST:event_SbtnLamMoiActionPerformed

    private void txtSĐTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSĐTKeyReleased
        // TODO add your handling code here:
        HoTroNhapSo.luonNhapSo(evt);
        lblvSDT.setVisible(false);
        
        
    }//GEN-LAST:event_txtSĐTKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.shady.scontrols.SButton SbtnLamMoi;
    private com.shady.scontrols.SButton SbtnSua;
    private com.shady.scontrols.SButton SbtnThem;
    private com.shady.scontrols.SButton SbtnXoa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblNhaCC;
    private javax.swing.JLabel lblSĐT;
    private javax.swing.JLabel lblTenNhaCC;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JLabel lblvDC;
    private javax.swing.JLabel lblvEmail;
    private javax.swing.JLabel lblvSDT;
    private javax.swing.JLabel lblvTenNCC;
    private com.shady.scontrols.STable tblDanhSach;
    private com.shady.scontrols.STextField txtDiaChi;
    private com.shady.scontrols.STextField txtEmail;
    private com.shady.scontrols.STextField txtGhiChu;
    private com.shady.scontrols.STextField txtMaNhaCC;
    private com.shady.scontrols.STextField txtSĐT;
    private com.shady.scontrols.STextField txtTenNhaCC;
    private com.shady.scontrols.STextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
