/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Du_An_DESIGN;

import Du_An_BLL.BLLCombobox;
import Du_An_BLL.BLLNhanVien;
import Du_An_DAL.DALNhanVien;
import Du_An_DTO.NhanVien;
import Du_An_HELPER.HoTroNhapSo;
import Du_An_HELPER.Mycombobox;
import Du_An_HELPER.SetImage;
import Du_An_HELPER.ThongBao;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author LENOVO
 */
public class TabNhanVien extends javax.swing.JPanel {

    
    SetImage img = new SetImage();
    /**
     * Creates new form TabNhanVien
     */
    public TabNhanVien() {
        initComponents();
        BLLNhanVien.LoadNhanVien(tblDanhSach);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        txtHinhAnh.setBackground(new Color(0, 0, 0, 0));
        //txtMaNhanVien.setText(BLLNhanVien.TaoSoHD());
        ResultSet rsLSP = DALNhanVien.getALLChucVu();
        BLLCombobox.Load(cbbMaChucVu, rsLSP, true);
        lbltest.setVisible(false);
        lblCM.setVisible(false);
        lblGmail.setVisible(false);
        lblSdt.setVisible(false);
        lblDC.setVisible(false);
        lblTenDN.setVisible(false);
        lblPass.setVisible(false);
        
        
       
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgGioiTinh = new javax.swing.ButtonGroup();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        lblMaChucVu = new javax.swing.JLabel();
        lblNgaySinh = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        lblTenNhanVien = new javax.swing.JLabel();
        lblMaNhanVien = new javax.swing.JLabel();
        txtMaNhanVien = new com.shady.scontrols.STextField();
        txtTenNhanVien = new com.shady.scontrols.STextField();
        rdbNu = new javax.swing.JRadioButton();
        rdbNam = new javax.swing.JRadioButton();
        txtNgaySinh = new com.toedter.calendar.JDateChooser();
        cbbMaChucVu = new javax.swing.JComboBox<>();
        lblNgayVaoLam = new javax.swing.JLabel();
        lblSĐT = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        lblCMND = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtSĐT = new com.shady.scontrols.STextField();
        txtDiaChi = new com.shady.scontrols.STextField();
        txtSoCMND = new com.shady.scontrols.STextField();
        txtEmail = new com.shady.scontrols.STextField();
        txtNgayVaoLam = new com.toedter.calendar.JDateChooser();
        lblTenDangNhap = new javax.swing.JLabel();
        lblMatKhau = new javax.swing.JLabel();
        txtTenDangNhap = new com.shady.scontrols.STextField();
        txtMatKhau = new com.shady.scontrols.STextField();
        lblHinhAnh = new javax.swing.JLabel();
        txtHinhAnh = new javax.swing.JTextField();
        SbtnChonHinh = new com.shady.scontrols.SButton();
        SbtnThem = new com.shady.scontrols.SButton();
        SbtnSua = new com.shady.scontrols.SButton();
        SbtnXoa = new com.shady.scontrols.SButton();
        SbtnLamMoi = new com.shady.scontrols.SButton();
        txtTimKiem = new com.shady.scontrols.STextField();
        lbltest = new javax.swing.JLabel();
        lblSdt = new javax.swing.JLabel();
        lblDC = new javax.swing.JLabel();
        lblCM = new javax.swing.JLabel();
        lblGmail = new javax.swing.JLabel();
        lblTenDN = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new com.shady.scontrols.STable();

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(203, 224, 255));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setOpaque(false);

        lblMaChucVu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMaChucVu.setForeground(new java.awt.Color(0, 0, 153));
        lblMaChucVu.setText("Mã Chức Vụ");

        lblNgaySinh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNgaySinh.setForeground(new java.awt.Color(0, 0, 153));
        lblNgaySinh.setText("Ngày Sinh");

        lblGioiTinh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGioiTinh.setForeground(new java.awt.Color(0, 0, 153));
        lblGioiTinh.setText("Giới Tính");

        lblTenNhanVien.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTenNhanVien.setForeground(new java.awt.Color(0, 0, 153));
        lblTenNhanVien.setText("Tên Nhân Viên");

        lblMaNhanVien.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMaNhanVien.setForeground(new java.awt.Color(0, 0, 153));
        lblMaNhanVien.setText("Mã Nhân Viên");

        txtMaNhanVien.setForeground(new java.awt.Color(0, 0, 153));
        txtMaNhanVien.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtMaNhanVien.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtMaNhanVien.sets_errorBackground(new java.awt.Color(255, 255, 255));
        txtMaNhanVien.sets_errorBorder(new java.awt.Color(255, 255, 255));
        txtMaNhanVien.sets_placeholder("Mời Bạn Nhập");
        txtMaNhanVien.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtMaNhanVien.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtMaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNhanVienActionPerformed(evt);
            }
        });

        txtTenNhanVien.setForeground(new java.awt.Color(0, 0, 153));
        txtTenNhanVien.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTenNhanVien.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtTenNhanVien.sets_placeholder("Mời Bạn Nhập");
        txtTenNhanVien.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtTenNhanVien.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtTenNhanVien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenNhanVienKeyReleased(evt);
            }
        });

        btgGioiTinh.add(rdbNu);
        rdbNu.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        rdbNu.setForeground(new java.awt.Color(0, 0, 153));
        rdbNu.setText("Nữ");
        rdbNu.setOpaque(false);

        btgGioiTinh.add(rdbNam);
        rdbNam.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        rdbNam.setForeground(new java.awt.Color(0, 0, 153));
        rdbNam.setSelected(true);
        rdbNam.setText("Nam");
        rdbNam.setOpaque(false);

        txtNgaySinh.setForeground(new java.awt.Color(0, 0, 204));
        txtNgaySinh.setDateFormatString("dd-MM-yyyy");
        txtNgaySinh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        cbbMaChucVu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbbMaChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân Viên", "Giám Đốc" }));

        lblNgayVaoLam.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNgayVaoLam.setForeground(new java.awt.Color(0, 0, 153));
        lblNgayVaoLam.setText("Ngày Vào Làm");

        lblSĐT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSĐT.setForeground(new java.awt.Color(0, 0, 153));
        lblSĐT.setText("Số Điện Thoai");

        lblDiaChi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDiaChi.setForeground(new java.awt.Color(0, 0, 153));
        lblDiaChi.setText("Địa Chỉ");

        lblCMND.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCMND.setForeground(new java.awt.Color(0, 0, 153));
        lblCMND.setText("CMND");

        lblEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 0, 153));
        lblEmail.setText("Email");

        txtSĐT.setForeground(new java.awt.Color(0, 0, 153));
        txtSĐT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSĐT.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtSĐT.sets_placeholder("Mời Bạn Nhập");
        txtSĐT.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtSĐT.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtSĐT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSĐTKeyReleased(evt);
            }
        });

        txtDiaChi.setForeground(new java.awt.Color(0, 0, 153));
        txtDiaChi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDiaChi.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtDiaChi.sets_placeholder("Mời Bạn Nhập");
        txtDiaChi.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtDiaChi.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });
        txtDiaChi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiaChiKeyReleased(evt);
            }
        });

        txtSoCMND.setForeground(new java.awt.Color(0, 0, 153));
        txtSoCMND.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSoCMND.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtSoCMND.sets_placeholder("Mời Bạn Nhập");
        txtSoCMND.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtSoCMND.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtSoCMND.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoCMNDKeyReleased(evt);
            }
        });

        txtEmail.setForeground(new java.awt.Color(0, 0, 153));
        txtEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEmail.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtEmail.sets_placeholder("Mời Bạn Nhập");
        txtEmail.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtEmail.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        txtNgayVaoLam.setForeground(new java.awt.Color(0, 0, 204));
        txtNgayVaoLam.setDateFormatString("dd-MM-yyyy");
        txtNgayVaoLam.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblTenDangNhap.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTenDangNhap.setForeground(new java.awt.Color(0, 0, 153));
        lblTenDangNhap.setText("Tên Đăng Nhập");

        lblMatKhau.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMatKhau.setForeground(new java.awt.Color(0, 0, 153));
        lblMatKhau.setText("Mật Khẩu");

        txtTenDangNhap.setForeground(new java.awt.Color(0, 0, 153));
        txtTenDangNhap.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTenDangNhap.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtTenDangNhap.sets_placeholder("Mời Bạn Nhập");
        txtTenDangNhap.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtTenDangNhap.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtTenDangNhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenDangNhapKeyReleased(evt);
            }
        });

        txtMatKhau.setForeground(new java.awt.Color(0, 0, 153));
        txtMatKhau.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMatKhau.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtMatKhau.sets_placeholder("Mời Bạn Nhập");
        txtMatKhau.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtMatKhau.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauActionPerformed(evt);
            }
        });
        txtMatKhau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMatKhauKeyReleased(evt);
            }
        });

        lblHinhAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinhAnh.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 204)));

        txtHinhAnh.setEditable(false);
        txtHinhAnh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtHinhAnh.setForeground(new java.awt.Color(0, 0, 153));
        txtHinhAnh.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(113, 117, 204)));

        SbtnChonHinh.setForeground(new java.awt.Color(0, 0, 204));
        SbtnChonHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/click.png"))); // NOI18N
        SbtnChonHinh.setText("Chọn Hình");
        SbtnChonHinh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SbtnChonHinh.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SbtnChonHinh.setIconTextGap(10);
        SbtnChonHinh.setMargin(new java.awt.Insets(5, 14, 5, 14));
        SbtnChonHinh.setMaximumSize(new java.awt.Dimension(70, 30));
        SbtnChonHinh.sets_borderColor(new java.awt.Color(153, 0, 153));
        SbtnChonHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnChonHinhActionPerformed(evt);
            }
        });

        SbtnThem.setForeground(new java.awt.Color(0, 0, 153));
        SbtnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/click.png"))); // NOI18N
        SbtnThem.setText("Thêm ");
        SbtnThem.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SbtnThem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SbtnThem.setIconTextGap(20);
        SbtnThem.setMargin(new java.awt.Insets(5, 14, 5, 14));
        SbtnThem.setMaximumSize(new java.awt.Dimension(70, 30));
        SbtnThem.sets_borderColor(new java.awt.Color(153, 0, 153));
        SbtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnThemActionPerformed(evt);
            }
        });

        SbtnSua.setForeground(new java.awt.Color(0, 0, 153));
        SbtnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/click.png"))); // NOI18N
        SbtnSua.setText("Sửa");
        SbtnSua.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SbtnSua.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SbtnSua.setIconTextGap(20);
        SbtnSua.setMargin(new java.awt.Insets(5, 14, 5, 14));
        SbtnSua.setMaximumSize(new java.awt.Dimension(70, 30));
        SbtnSua.sets_borderColor(new java.awt.Color(153, 0, 153));
        SbtnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnSuaActionPerformed(evt);
            }
        });

        SbtnXoa.setForeground(new java.awt.Color(0, 0, 153));
        SbtnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/click.png"))); // NOI18N
        SbtnXoa.setText("Xoá");
        SbtnXoa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SbtnXoa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SbtnXoa.setIconTextGap(20);
        SbtnXoa.setMargin(new java.awt.Insets(5, 14, 5, 14));
        SbtnXoa.setMaximumSize(new java.awt.Dimension(70, 30));
        SbtnXoa.sets_borderColor(new java.awt.Color(153, 0, 153));
        SbtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnXoaActionPerformed(evt);
            }
        });

        SbtnLamMoi.setForeground(new java.awt.Color(0, 0, 153));
        SbtnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/click.png"))); // NOI18N
        SbtnLamMoi.setText("Làm Mới");
        SbtnLamMoi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SbtnLamMoi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SbtnLamMoi.setIconTextGap(10);
        SbtnLamMoi.setMargin(new java.awt.Insets(5, 14, 5, 14));
        SbtnLamMoi.setMaximumSize(new java.awt.Dimension(70, 30));
        SbtnLamMoi.sets_borderColor(new java.awt.Color(153, 0, 153));
        SbtnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnLamMoiActionPerformed(evt);
            }
        });

        txtTimKiem.setForeground(new java.awt.Color(0, 0, 153));
        txtTimKiem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTimKiem.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtTimKiem.sets_placeholder("Mời Bạn Nhập Từ Khoá Cần Tìm");
        txtTimKiem.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtTimKiem.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        lbltest.setForeground(new java.awt.Color(255, 0, 0));

        lblSdt.setForeground(new java.awt.Color(255, 0, 0));

        lblDC.setForeground(new java.awt.Color(255, 0, 0));

        lblCM.setForeground(new java.awt.Color(255, 0, 0));

        lblGmail.setForeground(new java.awt.Color(255, 0, 0));

        lblTenDN.setForeground(new java.awt.Color(255, 0, 0));

        lblPass.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbbMaChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblMaChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(15, 15, 15)
                                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(15, 15, 15)
                                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(15, 15, 15)
                                    .addComponent(txtNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rdbNam, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(rdbNu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbltest))))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSĐT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTenDN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSoCMND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSĐT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTenDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSdt)
                    .addComponent(lblDC)
                    .addComponent(lblCM)
                    .addComponent(lblGmail)
                    .addComponent(lblPass))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHinhAnh)
                    .addComponent(SbtnChonHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SbtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SbtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SbtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SbtnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addComponent(lbltest)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(rdbNam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rdbNu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSĐT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSĐT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSdt)
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDC)
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addComponent(lblCM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(5, 5, 5)
                        .addComponent(lblGmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbMaChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(SbtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(SbtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(SbtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(SbtnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SbtnChonHinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPass)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        tblDanhSach.setBackground(new java.awt.Color(203, 224, 255));
        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Nhân Viên", "Tên Nhân Viên", "Giới Tính", "Ngày Sinh", "Chức Vụ", "Ngày Vào Làm", "Số Điện Thoại", "Địa Chỉ", "CMND", "Email", "Tên Đăng Ngập", "Mật Khẩu", "HÌnh Ảnh"
            }
        ));
        tblDanhSach.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSach);
        if (tblDanhSach.getColumnModel().getColumnCount() > 0) {
            tblDanhSach.getColumnModel().getColumn(0).setMinWidth(50);
            tblDanhSach.getColumnModel().getColumn(0).setMaxWidth(50);
            tblDanhSach.getColumnModel().getColumn(1).setMinWidth(0);
            tblDanhSach.getColumnModel().getColumn(1).setMaxWidth(0);
            tblDanhSach.getColumnModel().getColumn(3).setMinWidth(70);
            tblDanhSach.getColumnModel().getColumn(3).setMaxWidth(70);
            tblDanhSach.getColumnModel().getColumn(11).setMinWidth(0);
            tblDanhSach.getColumnModel().getColumn(11).setMaxWidth(0);
            tblDanhSach.getColumnModel().getColumn(12).setMinWidth(0);
            tblDanhSach.getColumnModel().getColumn(12).setMaxWidth(0);
            tblDanhSach.getColumnModel().getColumn(13).setMinWidth(0);
            tblDanhSach.getColumnModel().getColumn(13).setMaxWidth(0);
        }

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1)
                .addGap(20, 20, 20))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SbtnChonHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnChonHinhActionPerformed
        // TODO add your handling code here:
         JFileChooser fileChooser = new JFileChooser("image");
        FileFilter filter = new FileNameExtensionFilter("Image file", "gjf", "jpg", "png");

        fileChooser.setFileFilter(filter);
        fileChooser.setMultiSelectionEnabled(false);

        int action = fileChooser.showOpenDialog(this);
        if (action == JFileChooser.APPROVE_OPTION) {
            while (true) {
                if (!fileChooser.getSelectedFile().getName().matches("([^\\s]+(\\.(?i)(jpg|png|gif|bmp))$)")) {
                    JOptionPane.showMessageDialog(null, "Định dạng file hình đuôi phải là GIF, JPG, PNG !");
                    return;
                } else {
                    break;
                }
            }
            String imgFile = fileChooser.getSelectedFile().getName();
            txtHinhAnh.setText(imgFile);
            img.setImageLabel(lblHinhAnh, "image//" + imgFile);
        }

    }//GEN-LAST:event_SbtnChonHinhActionPerformed

    private void SbtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnThemActionPerformed
        txtMaNhanVien.setText(BLLNhanVien.TaoMaNV());
        String MaNV = txtMaNhanVien.getText();
        String TenNV = txtTenNhanVien.getText();
        boolean GioiTinh = rdbNam.isSelected();
        Date NgaySinh = txtNgaySinh.getDate();
        String ChucVu;
            Mycombobox myCbb = (Mycombobox) cbbMaChucVu.getSelectedItem();
            ChucVu = myCbb.MaString();
        //double Luong = ChuyenDoi.LaySoDouble(txtLuong.getText());
        String SDT = txtSĐT.getText();
        String DiaChi = txtDiaChi.getText();
        String SoCMND = txtSoCMND.getText();
        Date NgayVaoLam = txtNgayVaoLam.getDate();
        String TenDangNhap = txtTenDangNhap.getText();
        String MatKhau = txtMatKhau.getText();
        String HinhAnh = txtHinhAnh.getText();
        String Email = txtEmail.getText();
        
        if(this.txtTenNhanVien.getText().length() == 0 || this.txtDiaChi.getText().length() == 0 ||
           this.txtSoCMND.getText().length() == 0 || this.txtEmail.getText().length() == 0 ||
           this.txtSĐT.getText().length() == 0 || this.txtTenDangNhap.getText().length() == 0 ||
           this.txtMatKhau.getText().length() == 0
                ) {
        if (this.txtTenNhanVien.getText().length() == 0) {
            
            lbltest.setVisible(true);
            lbltest.setText("Họ Và Tên Không Được Bỏ Trống");
        }  
        if (this.txtDiaChi.getText().length() == 0) {
            lblDC.setVisible(true);
            lblDC.setText("Địa Chỉ Không Được Bỏ Trống");
        }  
        if (this.txtSoCMND.getText().length() == 0) {
            lblCM.setVisible(true);
            lblCM.setText("Số CMND Không Được Bỏ Trống");
        }  
        if (this.txtEmail.getText().length() == 0) {
            lblGmail.setVisible(true);
            lblGmail.setText("Email Không Được Bỏ Trống");
        } 
        if (this.txtSĐT.getText().length() == 0) {
            lblSdt.setVisible(true);
            lblSdt.setText("Số Điện Thoại Không Được Bỏ Trống");
        }
        if (this.txtTenDangNhap.getText().length() == 0) {
            lblTenDN.setVisible(true);
            lblTenDN.setText("Tên Đăng Nhập Không Được Bỏ Trống");
        }
        if (this.txtMatKhau.getText().length() == 0) {
            lblPass.setVisible(true);
            lblPass.setText("Mật Khẩu Không Được Bỏ Trống");
        }
        }else {
            
            NhanVien nv = new NhanVien(MaNV, TenNV, GioiTinh, NgaySinh, ChucVu, DiaChi, SDT, SoCMND, NgayVaoLam, TenDangNhap, MatKhau, Email, HinhAnh);

            BLLNhanVien.ThemNhanVien(nv);
             ThongBao.ThongBaoDangNhap("Thông Báo", " Thêm Thành Công");
            BLLNhanVien.LoadNhanVien(tblDanhSach);
        }
    }//GEN-LAST:event_SbtnThemActionPerformed

    private void CbbChonCV(String TenLoaiSP) {
        DefaultComboBoxModel cbbModel = (DefaultComboBoxModel) cbbMaChucVu.getModel();

        for (int i = 0; i < cbbMaChucVu.getItemCount(); i++) {
            Mycombobox myCBB = (Mycombobox) cbbModel.getElementAt(i);

            if (myCBB.MaString().toString().equals(TenLoaiSP)) {
                cbbMaChucVu.setSelectedIndex(i);
                break;
            }
        }
    }
    
    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
       int dongDuocChon = tblDanhSach.getSelectedRow();
        String MaNV = tblDanhSach.getValueAt(dongDuocChon, 1).toString();
        NhanVien nv = BLLNhanVien.LayNhanVienTheoMa(MaNV);
        txtMaNhanVien.setText(nv.getMaNV() + "");
        String image = (String) tblDanhSach.getValueAt(dongDuocChon, 13);

        //   cbbMaChucVu.setSelectedItem(nv.getMaChucVu());
        //BLLCombobox.setComboSelectValue(cbbMaChucVu, nv.getChucVu());
        txtTenNhanVien.setText(nv.getTenNV());
        if (nv.isGioiTinh()) {
            rdbNam.setSelected(true);
        } else {
            rdbNu.setSelected(true);
        }

        txtNgaySinh.setDate(nv.getNgaySinh());
        txtDiaChi.setText(nv.getDiaChi());
        txtSĐT.setText(nv.getSDT());
        txtSoCMND.setText(nv.getCMND());
        txtEmail.setText(nv.getEmail());
        txtTenDangNhap.setText(nv.getTenDangNhap());
        txtMatKhau.setText(nv.getMatKhau());
        txtNgayVaoLam.setDate(nv.getNgayVaoLam());
        txtHinhAnh.setText(image);
        CbbChonCV(nv.getChucVu());
        img.setImageLabel(lblHinhAnh, "image//" + image);

        // Chuyển Về Tab Đầu Tiên
        lblHinhAnh.setText("");
    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void SbtnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnLamMoiActionPerformed
        
        this.txtMaNhanVien.setText("");
        this.txtTenNhanVien.setText("");
        this.txtDiaChi.setText("");
        this.txtSĐT.setText("");
        this.txtSoCMND.setText("");
        this.txtMatKhau.setText("");
        //this.txtThongBao.setText("");
        this.txtTenDangNhap.setText("");
         this.txtEmail.setText("");
         
         lbltest.setVisible(false);
        lblCM.setVisible(false);
        lblGmail.setVisible(false);
        lblSdt.setVisible(false);
        lblDC.setVisible(false);
        lblTenDN.setVisible(false);
        lblPass.setVisible(false);
    }//GEN-LAST:event_SbtnLamMoiActionPerformed

    private void SbtnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnSuaActionPerformed
        String MaNV = txtMaNhanVien.getText();
        String TenNV = txtTenNhanVien.getText();
        boolean GioiTinh = rdbNam.isSelected();
        Date NgaySinh = txtNgaySinh.getDate();
        String ChucVu;
            Mycombobox myCbb = (Mycombobox) cbbMaChucVu.getSelectedItem();
            ChucVu = myCbb.MaString();
        //double Luong = ChuyenDoi.LaySoDouble(txtLuong.getText());
        String SDT = txtSĐT.getText();
        String DiaChi = txtDiaChi.getText();
        String SoCMND = txtSoCMND.getText();
        Date NgayVaoLam = txtNgayVaoLam.getDate();
        String TenDangNhap = txtTenDangNhap.getText();
        String MatKhau = txtMatKhau.getText();
        String HinhAnh = txtHinhAnh.getText();
        String Email = txtEmail.getText();
        if (this.txtTenNhanVien.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Họ Và Tên Không Được Bỏ Trống");
        } else if (this.txtDiaChi.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Địa Chỉ Không Được Bỏ Trống");
        } else if (this.txtSoCMND.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Số CMND Không Được Bỏ Trống");
        } else if (this.txtEmail.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", " Email Không Được Bỏ Trống");
        } else if (this.txtSĐT.getText().length() < 10) {
            ThongBao.ThongBaoSQL("Thông Báo", "Số Điện Thoại Được Bỏ Trống");
        } else if (this.txtTenDangNhap.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Tên Đăng Nhập Được Bỏ Trống");
        } else if (this.txtMatKhau.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", "Mật Khẩu Được Bỏ Trống");
        } else {
            NhanVien nv = new NhanVien(MaNV, TenNV, GioiTinh, NgaySinh, ChucVu, DiaChi, SDT, SoCMND, NgayVaoLam, TenDangNhap, MatKhau, Email, HinhAnh);

            BLLNhanVien.SuaNhanVien(nv);
             ThongBao.ThongBaoDangNhap("Thông Báo", " Đã Sửa Thành Công");
            BLLNhanVien.LoadNhanVien(tblDanhSach);
        }
    }//GEN-LAST:event_SbtnSuaActionPerformed

    private void SbtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnXoaActionPerformed
        if (this.txtMaNhanVien.getText().length() == 0) {
            ThongBao.ThongBaoSQL("Thông Báo", " Bạn Chưa Chọn Dòng Để Xoá !!");

        } else {

            int DSViTri[] = tblDanhSach.getSelectedRows();
            List<String> lstMaSP = new ArrayList<>();

            for (int i : DSViTri) {
                String MaNV = tblDanhSach.getValueAt(i, 1).toString();
                lstMaSP.add(MaNV);
            }

            BLLNhanVien.Delete(lstMaSP);
             ThongBao.ThongBaoDangNhap("Thông Báo", " Xóa Thành Công");

            BLLNhanVien.LoadNhanVien(tblDanhSach);
        }
    }//GEN-LAST:event_SbtnXoaActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        String TenNhanVien = "%" + txtTimKiem.getText() + "%";
       
        BLLNhanVien.TimNhanVien(tblDanhSach, TenNhanVien);
        
        
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void txtMaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNhanVienActionPerformed

    private void txtSoCMNDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoCMNDKeyReleased
        HoTroNhapSo.luonNhapSo(evt);
        lblCM.setVisible(false);
    }//GEN-LAST:event_txtSoCMNDKeyReleased

    private void txtSĐTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSĐTKeyReleased
        HoTroNhapSo.luonNhapSo(evt);
        lblSdt.setVisible(false);
    }//GEN-LAST:event_txtSĐTKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        String Email_Pattern = "^[a-zA-Z0-9]{0,30}[@][a-zA-z0-9]{0,10}[.][a-zA-Z]{2,5}$";
        Pattern pattern = Pattern.compile(Email_Pattern);
        Matcher matcher = pattern.matcher(txtEmail.getText());
        if (!matcher.matches()) {
            lblGmail.setText("Email không đúng định Dạng");
        } else {
            lblGmail.setVisible(false);
        }
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtTenNhanVienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenNhanVienKeyReleased
        lbltest.setVisible(false);
    }//GEN-LAST:event_txtTenNhanVienKeyReleased

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void txtDiaChiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaChiKeyReleased
       lblDC.setVisible(false);
    }//GEN-LAST:event_txtDiaChiKeyReleased

    private void txtTenDangNhapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenDangNhapKeyReleased
        lblTenDN.setVisible(false);
    }//GEN-LAST:event_txtTenDangNhapKeyReleased

    private void txtMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatKhauActionPerformed

    private void txtMatKhauKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatKhauKeyReleased
      lblMatKhau.setVisible(false);
    }//GEN-LAST:event_txtMatKhauKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.shady.scontrols.SButton SbtnChonHinh;
    private com.shady.scontrols.SButton SbtnLamMoi;
    private com.shady.scontrols.SButton SbtnSua;
    private com.shady.scontrols.SButton SbtnThem;
    private com.shady.scontrols.SButton SbtnXoa;
    private javax.swing.ButtonGroup btgGioiTinh;
    private javax.swing.JComboBox<String> cbbMaChucVu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblCM;
    private javax.swing.JLabel lblCMND;
    private javax.swing.JLabel lblDC;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblGmail;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JLabel lblMaChucVu;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblNgayVaoLam;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblSdt;
    private javax.swing.JLabel lblSĐT;
    private javax.swing.JLabel lblTenDN;
    private javax.swing.JLabel lblTenDangNhap;
    private javax.swing.JLabel lblTenNhanVien;
    private javax.swing.JLabel lbltest;
    private javax.swing.JRadioButton rdbNam;
    private javax.swing.JRadioButton rdbNu;
    private com.shady.scontrols.STable tblDanhSach;
    private com.shady.scontrols.STextField txtDiaChi;
    private com.shady.scontrols.STextField txtEmail;
    private javax.swing.JTextField txtHinhAnh;
    private com.shady.scontrols.STextField txtMaNhanVien;
    private com.shady.scontrols.STextField txtMatKhau;
    private com.toedter.calendar.JDateChooser txtNgaySinh;
    private com.toedter.calendar.JDateChooser txtNgayVaoLam;
    private com.shady.scontrols.STextField txtSoCMND;
    private com.shady.scontrols.STextField txtSĐT;
    private com.shady.scontrols.STextField txtTenDangNhap;
    private com.shady.scontrols.STextField txtTenNhanVien;
    private com.shady.scontrols.STextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
