/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Du_An_DESIGN;

import Du_An_BLL.BLLCombobox;
import Du_An_BLL.BLLHangSX;
import Du_An_BLL.BLLLoaiSP;
import Du_An_BLL.BLLSanPham;
import Du_An_DAL.DALHangSX;
import Du_An_DAL.DALLoaiSP;
import Du_An_DAL.DALSanPham;
import Du_An_DTO.SanPham;
import Du_An_HELPER.ChuyenDoi;
import Du_An_HELPER.HoTroNhapSo;
import Du_An_HELPER.Mycombobox;
import Du_An_HELPER.SetImage;
import Du_An_HELPER.ThongBao;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author LENOVO
 */
public class TabSanPham extends javax.swing.JPanel {
    SetImage img = new SetImage();
    /**
     * Creates new form frmSanPham
     */
    public TabSanPham() {
        initComponents();
        BLLSanPham.LoadSanPham(tblDanhSach);
        ResultSet rsLSP = DALLoaiSP.GetAll();
        BLLCombobox.Load(cbbLoaiSP, rsLSP, true);
        ResultSet rsHSX = DALHangSX.GetAll();
        BLLCombobox.Load(cbbHangSX, rsHSX, true);
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        txtHinhAnh.setBackground(new Color(0, 0, 0, 0));
        lblTensp.setVisible(false);
        lblVSoLuong.setVisible(false);
        lblvGiaNhap.setVisible(false);
        lblvGiaBan.setVisible(false);
        lblvTGBH.setVisible(false);
        lblvGiaBan1.setVisible(false);
        lblVSoLuong1.setVisible(false);
        lblVSoLuong2.setVisible(false);
        lblVSoLuong3.setVisible(false);
        lblTensp1.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        lblSanPham = new javax.swing.JLabel();
        txtMaSanPham = new com.shady.scontrols.STextField();
        txtTenSanPham = new com.shady.scontrols.STextField();
        lblTenSanPham = new javax.swing.JLabel();
        txtSoLuong = new com.shady.scontrols.STextField();
        lblSoLuong = new javax.swing.JLabel();
        lblDonViTinh = new javax.swing.JLabel();
        txtGiaNhap = new com.shady.scontrols.STextField();
        lblGiaNhap = new javax.swing.JLabel();
        lblNgayNhap = new javax.swing.JLabel();
        txtGiaBan = new com.shady.scontrols.STextField();
        lblGiaBan = new javax.swing.JLabel();
        llblMLSP = new javax.swing.JLabel();
        lblMHSX = new javax.swing.JLabel();
        lblThoiGianBaoHanh = new javax.swing.JLabel();
        SbtnXoa = new com.shady.scontrols.SButton();
        SbtnThem = new com.shady.scontrols.SButton();
        SbtnLamMoi = new com.shady.scontrols.SButton();
        SbtnSua = new com.shady.scontrols.SButton();
        lblGhiChu = new javax.swing.JLabel();
        txtGhiChu = new com.shady.scontrols.STextField();
        txtTimKiem = new com.shady.scontrols.STextField();
        txtNgayNhap = new com.toedter.calendar.JDateChooser();
        lblHinhAnh = new javax.swing.JLabel();
        txtHinhAnh = new javax.swing.JTextField();
        SbtnChonHinh = new com.shady.scontrols.SButton();
        cbbDVT = new javax.swing.JComboBox<>();
        cbbLoaiSP = new javax.swing.JComboBox<>();
        btnLoaiSP = new javax.swing.JButton();
        cbbHangSX = new javax.swing.JComboBox<>();
        btnHangSX = new javax.swing.JButton();
        txtThoiGianBH = new com.shady.scontrols.STextField();
        lblGhiChu1 = new javax.swing.JLabel();
        lblTensp = new javax.swing.JLabel();
        lblVSoLuong = new javax.swing.JLabel();
        lblvGiaBan = new javax.swing.JLabel();
        lblvTGBH = new javax.swing.JLabel();
        lblvGiaNhap = new javax.swing.JLabel();
        lblvGiaBan1 = new javax.swing.JLabel();
        lblTensp1 = new javax.swing.JLabel();
        lblVSoLuong1 = new javax.swing.JLabel();
        lblVSoLuong2 = new javax.swing.JLabel();
        lblVSoLuong3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new com.shady.scontrols.STable();

        setForeground(new java.awt.Color(255, 0, 51));

        kGradientPanel1.setkEndColor(new java.awt.Color(203, 224, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setOpaque(false);

        lblSanPham.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSanPham.setForeground(new java.awt.Color(0, 0, 153));
        lblSanPham.setText("Mã Sản Phẩm");

        txtMaSanPham.setForeground(new java.awt.Color(0, 0, 153));
        txtMaSanPham.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtMaSanPham.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtMaSanPham.sets_errorBackground(new java.awt.Color(255, 255, 255));
        txtMaSanPham.sets_errorBorder(new java.awt.Color(255, 255, 255));
        txtMaSanPham.sets_placeholder("Mời Bạn Nhập");
        txtMaSanPham.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtMaSanPham.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));

        txtTenSanPham.setForeground(new java.awt.Color(0, 0, 153));
        txtTenSanPham.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTenSanPham.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtTenSanPham.sets_errorBackground(new java.awt.Color(255, 255, 255));
        txtTenSanPham.sets_errorBorder(new java.awt.Color(255, 255, 255));
        txtTenSanPham.sets_placeholder("Mời Bạn Nhập");
        txtTenSanPham.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtTenSanPham.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtTenSanPham.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenSanPhamKeyReleased(evt);
            }
        });

        lblTenSanPham.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTenSanPham.setForeground(new java.awt.Color(0, 0, 153));
        lblTenSanPham.setText("Tên Sản Phẩm");

        txtSoLuong.setForeground(new java.awt.Color(0, 0, 153));
        txtSoLuong.setText("1");
        txtSoLuong.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSoLuong.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtSoLuong.sets_errorBackground(new java.awt.Color(255, 255, 255));
        txtSoLuong.sets_errorBorder(new java.awt.Color(255, 255, 255));
        txtSoLuong.sets_placeholder("Mời Bạn Nhập");
        txtSoLuong.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtSoLuong.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });
        txtSoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoLuongKeyReleased(evt);
            }
        });

        lblSoLuong.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSoLuong.setForeground(new java.awt.Color(0, 0, 153));
        lblSoLuong.setText("Số Lượng");

        lblDonViTinh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDonViTinh.setForeground(new java.awt.Color(0, 0, 153));
        lblDonViTinh.setText("Đơn Vị Tính");

        txtGiaNhap.setForeground(new java.awt.Color(0, 0, 153));
        txtGiaNhap.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtGiaNhap.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtGiaNhap.sets_errorBackground(new java.awt.Color(255, 255, 255));
        txtGiaNhap.sets_errorBorder(new java.awt.Color(255, 255, 255));
        txtGiaNhap.sets_placeholder("Mời Bạn Nhập");
        txtGiaNhap.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtGiaNhap.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtGiaNhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGiaNhapKeyReleased(evt);
            }
        });

        lblGiaNhap.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGiaNhap.setForeground(new java.awt.Color(0, 0, 153));
        lblGiaNhap.setText("Giá Nhập");

        lblNgayNhap.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNgayNhap.setForeground(new java.awt.Color(0, 0, 153));
        lblNgayNhap.setText("Ngày Nhập");

        txtGiaBan.setForeground(new java.awt.Color(0, 0, 153));
        txtGiaBan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtGiaBan.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtGiaBan.sets_errorBackground(new java.awt.Color(255, 255, 255));
        txtGiaBan.sets_errorBorder(new java.awt.Color(255, 255, 255));
        txtGiaBan.sets_placeholder("Mời Bạn Nhập");
        txtGiaBan.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtGiaBan.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtGiaBan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGiaBanKeyReleased(evt);
            }
        });

        lblGiaBan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGiaBan.setForeground(new java.awt.Color(0, 0, 153));
        lblGiaBan.setText("Giá Bán");

        llblMLSP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        llblMLSP.setForeground(new java.awt.Color(0, 0, 153));
        llblMLSP.setText("Loại Sản Phẩm");

        lblMHSX.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMHSX.setForeground(new java.awt.Color(0, 0, 153));
        lblMHSX.setText("Hãng Sản Xuất");

        lblThoiGianBaoHanh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblThoiGianBaoHanh.setForeground(new java.awt.Color(0, 0, 153));
        lblThoiGianBaoHanh.setText("Thời Gian Bảo Hành");

        SbtnXoa.setForeground(new java.awt.Color(0, 0, 153));
        SbtnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/click.png"))); // NOI18N
        SbtnXoa.setText("Xoá");
        SbtnXoa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SbtnXoa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SbtnXoa.setIconTextGap(20);
        SbtnXoa.setMargin(new java.awt.Insets(5, 14, 5, 14));
        SbtnXoa.setMaximumSize(new java.awt.Dimension(70, 30));
        SbtnXoa.sets_borderColor(new java.awt.Color(153, 0, 153));
        SbtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnXoaActionPerformed(evt);
            }
        });

        SbtnThem.setForeground(new java.awt.Color(0, 0, 153));
        SbtnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/click.png"))); // NOI18N
        SbtnThem.setText("Thêm ");
        SbtnThem.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SbtnThem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SbtnThem.setIconTextGap(20);
        SbtnThem.setMargin(new java.awt.Insets(5, 14, 5, 14));
        SbtnThem.setMaximumSize(new java.awt.Dimension(70, 30));
        SbtnThem.sets_borderColor(new java.awt.Color(153, 0, 153));
        SbtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnThemActionPerformed(evt);
            }
        });

        SbtnLamMoi.setForeground(new java.awt.Color(0, 0, 153));
        SbtnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/click.png"))); // NOI18N
        SbtnLamMoi.setText("Làm Mới");
        SbtnLamMoi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SbtnLamMoi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SbtnLamMoi.setIconTextGap(10);
        SbtnLamMoi.setMargin(new java.awt.Insets(5, 14, 5, 14));
        SbtnLamMoi.setMaximumSize(new java.awt.Dimension(70, 30));
        SbtnLamMoi.sets_borderColor(new java.awt.Color(153, 0, 153));
        SbtnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnLamMoiActionPerformed(evt);
            }
        });

        SbtnSua.setForeground(new java.awt.Color(0, 0, 153));
        SbtnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/click.png"))); // NOI18N
        SbtnSua.setText("Sửa");
        SbtnSua.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SbtnSua.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SbtnSua.setIconTextGap(20);
        SbtnSua.setMargin(new java.awt.Insets(5, 14, 5, 14));
        SbtnSua.setMaximumSize(new java.awt.Dimension(70, 30));
        SbtnSua.sets_borderColor(new java.awt.Color(153, 0, 153));
        SbtnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnSuaActionPerformed(evt);
            }
        });

        lblGhiChu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGhiChu.setForeground(new java.awt.Color(0, 0, 153));
        lblGhiChu.setText("Ghi Chú");

        txtGhiChu.setForeground(new java.awt.Color(0, 0, 153));
        txtGhiChu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtGhiChu.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtGhiChu.sets_errorBackground(new java.awt.Color(255, 255, 255));
        txtGhiChu.sets_errorBorder(new java.awt.Color(255, 255, 255));
        txtGhiChu.sets_placeholder("Ghi Chú");
        txtGhiChu.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtGhiChu.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));

        txtTimKiem.setForeground(new java.awt.Color(0, 0, 153));
        txtTimKiem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTimKiem.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtTimKiem.sets_placeholder("Mời Bạn Nhập Từ Khoá Cần Tìm");
        txtTimKiem.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtTimKiem.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        txtNgayNhap.setForeground(new java.awt.Color(0, 0, 204));
        txtNgayNhap.setDateFormatString("dd-MM-yyyy");
        txtNgayNhap.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblHinhAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinhAnh.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 204)));

        txtHinhAnh.setEditable(false);
        txtHinhAnh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtHinhAnh.setForeground(new java.awt.Color(0, 0, 153));
        txtHinhAnh.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(113, 117, 204)));
        txtHinhAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHinhAnhActionPerformed(evt);
            }
        });

        SbtnChonHinh.setForeground(new java.awt.Color(0, 0, 204));
        SbtnChonHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Du_An_IMAGES/click.png"))); // NOI18N
        SbtnChonHinh.setText("Chọn Hình");
        SbtnChonHinh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SbtnChonHinh.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SbtnChonHinh.setIconTextGap(10);
        SbtnChonHinh.setMargin(new java.awt.Insets(5, 14, 5, 14));
        SbtnChonHinh.setMaximumSize(new java.awt.Dimension(70, 30));
        SbtnChonHinh.sets_borderColor(new java.awt.Color(153, 0, 153));
        SbtnChonHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnChonHinhActionPerformed(evt);
            }
        });

        cbbDVT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn", "Thanh", "Cái", "Bộ" }));

        cbbLoaiSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnLoaiSP.setText("+");
        btnLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiSPActionPerformed(evt);
            }
        });

        cbbHangSX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnHangSX.setText("+");
        btnHangSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHangSXActionPerformed(evt);
            }
        });

        txtThoiGianBH.setForeground(new java.awt.Color(0, 0, 153));
        txtThoiGianBH.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtThoiGianBH.sets_BgColor(new java.awt.Color(203, 224, 255));
        txtThoiGianBH.sets_errorBackground(new java.awt.Color(255, 255, 255));
        txtThoiGianBH.sets_errorBorder(new java.awt.Color(255, 255, 255));
        txtThoiGianBH.sets_placeholder("Mời Bạn Nhập");
        txtThoiGianBH.sets_placeholderFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtThoiGianBH.sets_placeholderForeGround(new java.awt.Color(204, 0, 255));
        txtThoiGianBH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtThoiGianBHKeyReleased(evt);
            }
        });

        lblGhiChu1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGhiChu1.setForeground(new java.awt.Color(0, 0, 153));
        lblGhiChu1.setText("Tìm Kiếm");

        lblTensp.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        lblTensp.setForeground(new java.awt.Color(255, 0, 51));
        lblTensp.setText("jLabel1");

        lblVSoLuong.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        lblVSoLuong.setForeground(new java.awt.Color(255, 0, 51));
        lblVSoLuong.setText("jLabel2");

        lblvGiaBan.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        lblvGiaBan.setForeground(new java.awt.Color(255, 0, 51));
        lblvGiaBan.setText("jLabel3");

        lblvTGBH.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        lblvTGBH.setForeground(new java.awt.Color(255, 0, 51));
        lblvTGBH.setText("jLabel5");

        lblvGiaNhap.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        lblvGiaNhap.setForeground(new java.awt.Color(255, 0, 51));
        lblvGiaNhap.setText("jLabel6");

        lblvGiaBan1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        lblvGiaBan1.setForeground(new java.awt.Color(255, 0, 51));
        lblvGiaBan1.setText("jLabel3");

        lblTensp1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        lblTensp1.setForeground(new java.awt.Color(255, 0, 51));
        lblTensp1.setText("jLabel1");

        lblVSoLuong1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        lblVSoLuong1.setForeground(new java.awt.Color(255, 0, 51));
        lblVSoLuong1.setText("jLabel2");

        lblVSoLuong2.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        lblVSoLuong2.setForeground(new java.awt.Color(255, 0, 51));
        lblVSoLuong2.setText("jLabel2");

        lblVSoLuong3.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        lblVSoLuong3.setForeground(new java.awt.Color(255, 0, 51));
        lblVSoLuong3.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblvGiaBan1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(llblMLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblThoiGianBaoHanh, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMHSX, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblvGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblTensp1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(10, 10, 10))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cbbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtNgayNhap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtGiaBan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblVSoLuong1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVSoLuong3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblvTGBH, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtThoiGianBH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(cbbHangSX, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnHangSX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(65, 65, 65))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDonViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGhiChu1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTensp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVSoLuong2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblvGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SbtnChonHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(txtHinhAnh, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHinhAnh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SbtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SbtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SbtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SbtnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblvGiaBan1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblvGiaBan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTensp, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTensp1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(llblMLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVSoLuong1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDonViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMHSX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbHangSX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHangSX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVSoLuong2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVSoLuong3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThoiGianBH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblThoiGianBaoHanh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblvGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblvTGBH, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SbtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(SbtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(SbtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(SbtnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SbtnChonHinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGhiChu1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        tblDanhSach.setBackground(new java.awt.Color(203, 224, 255));
        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Đơn Vị Tính", "Giá Nhập", "Giá Bán", "Ngày Nhập", "ML Sản Phẩm", "MH Sản Xuất", "TG Bảo Hành", "HÌnh Ảnh", "Ghi Chú"
            }
        ));
        tblDanhSach.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSach);
        if (tblDanhSach.getColumnModel().getColumnCount() > 0) {
            tblDanhSach.getColumnModel().getColumn(0).setMinWidth(50);
            tblDanhSach.getColumnModel().getColumn(0).setMaxWidth(50);
            tblDanhSach.getColumnModel().getColumn(1).setMinWidth(0);
            tblDanhSach.getColumnModel().getColumn(1).setMaxWidth(0);
            tblDanhSach.getColumnModel().getColumn(11).setMinWidth(0);
            tblDanhSach.getColumnModel().getColumn(11).setMaxWidth(0);
        }

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1)
                .addGap(20, 20, 20))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1246, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SbtnChonHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnChonHinhActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser("image");
        FileFilter filter = new FileNameExtensionFilter("Image file", "gjf", "jpg", "png");

        fileChooser.setFileFilter(filter);
        fileChooser.setMultiSelectionEnabled(false);

        int action = fileChooser.showOpenDialog(this);
        if (action == JFileChooser.APPROVE_OPTION) {
            while (true) {
                if (!fileChooser.getSelectedFile().getName().matches("([^\\s]+(\\.(?i)(jpg|png|gif|bmp))$)")) {
                    JOptionPane.showMessageDialog(null, "Định dạng file hình đuôi phải là GIF, JPG, PNG !");
                    return;
                } else {
                    break;
                }
            }
            String imgFile = fileChooser.getSelectedFile().getName();
            txtHinhAnh.setText(imgFile);
            img.setImageLabel(lblHinhAnh, "image//" + imgFile);
        }
    }//GEN-LAST:event_SbtnChonHinhActionPerformed
    
    
    private void CbbChonLoaiSP(String TenLoaiSP) {
        DefaultComboBoxModel cbbModel = (DefaultComboBoxModel) cbbLoaiSP.getModel();

        for (int i = 0; i < cbbLoaiSP.getItemCount(); i++) {
            Mycombobox myCBB = (Mycombobox) cbbModel.getElementAt(i);

            if (myCBB.MaString().toString().equals(TenLoaiSP)) {
                cbbLoaiSP.setSelectedIndex(i);
                break;
            }
        }
    }

    private void CbbChonHangSX(String TenHangSX) {
        DefaultComboBoxModel cbbModel = (DefaultComboBoxModel) cbbHangSX.getModel();

        for (int i = 0; i < cbbHangSX.getItemCount(); i++) {
            Mycombobox myCBB = (Mycombobox) cbbModel.getElementAt(i);

            if (myCBB.MaString().toString().equals(TenHangSX)) {
                cbbHangSX.setSelectedIndex(i);
                break;
            }
        }
    }
    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        int dongDuocChon = tblDanhSach.getSelectedRow();
        String MaNV = tblDanhSach.getValueAt(dongDuocChon, 1).toString();
        SanPham sp = BLLSanPham.LaySanPhamTheoMa(MaNV);
        txtMaSanPham.setText(sp.getMaSanPham() + "");
        String image = (String) tblDanhSach.getValueAt(dongDuocChon, 11);

        txtTenSanPham.setText(sp.getTenSanPham());
        txtSoLuong.setText(ChuyenDoi.LaySoString(sp.getSoLuong()));
        cbbDVT.setSelectedItem(sp.getDonViTinh());
        txtGiaNhap.setText(ChuyenDoi.LaySoString(sp.getGiaNhap()));
        txtGiaBan.setText(ChuyenDoi.LaySoString(sp.getGiaBan()));
        //cbbLoaiSP.setSelectedItem(sp.getMaLoaiSp());
        CbbChonLoaiSP(sp.getMaLoaiSP());
        //cbbChucVu.setSelectedItem(nv.getChucvu());
        //cbbHangSX.setSelectedItem(sp.getMaHangSx());
        CbbChonHangSX(sp.getMaHangSX());
        txtNgayNhap.setDate(sp.getNgayNhap());
        txtHinhAnh.setText(image);
        txtThoiGianBH.setText(sp.getThoiGianBH());
        img.setImageLabel(lblHinhAnh, "image//" + image);
        //Chuyển tab về đầu tiên
        lblHinhAnh.setText("");
    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void btnLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiSPActionPerformed
        jdlLoaiSanPham jdl = new jdlLoaiSanPham((JFrame) SwingUtilities.getWindowAncestor(this), true);
        jdl.setVisible(true);
        String KeyWord = "";
        BLLLoaiSP.DoDuLieuVaoCBBLoaiSP(cbbLoaiSP, KeyWord);
    }//GEN-LAST:event_btnLoaiSPActionPerformed

    private void btnHangSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHangSXActionPerformed
        jdlHangSX jdl = new jdlHangSX((JFrame) SwingUtilities.getWindowAncestor(this), true);
        jdl.setVisible(true);

        String KeyWord = "";
        BLLHangSX.DoDuLieuVaoCBBHangSX(cbbHangSX, KeyWord);
    }//GEN-LAST:event_btnHangSXActionPerformed

    private void SbtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnThemActionPerformed
        
            int SoLuong;
            txtMaSanPham.setText(BLLSanPham.TaoSP());
            String MaSP = txtMaSanPham.getText();
            String TenSanPham = txtTenSanPham.getText();
            SoLuong = Integer.parseInt(txtSoLuong.getText());
            String DonViTinh = cbbDVT.getSelectedItem().toString();
            double GiaNhap = ChuyenDoi.LaySoDouble(txtGiaNhap.getText());
            double GiaBan = ChuyenDoi.LaySoDouble(txtGiaBan.getText());
            Date NgayNhap = txtNgayNhap.getDate();
            String MaLoaiSp;
            Mycombobox myCbb = (Mycombobox) cbbLoaiSP.getSelectedItem();
            MaLoaiSp = myCbb.MaString();
            String HangSX;
            Mycombobox mycbb = (Mycombobox) cbbHangSX.getSelectedItem();
            HangSX = mycbb.MaString();
            String ThoiGianBH = txtThoiGianBH.getText();
            String HinhAnh = txtHinhAnh.getText();
            String GhiChu = txtGhiChu.getText();
        if(this.txtTenSanPham.getText().length() == 0 || this.txtSoLuong.getText().length() == 0 ||
                
           this.txtGiaNhap.getText().length() == 0 || this.txtGiaBan.getText().length() == 0 ||
           this.txtThoiGianBH.getText().length() == 0 
                ) {
        
            if (this.txtTenSanPham.getText().length() == 0) {
            lblTensp.setVisible(true);
            lblTensp.setText("Tên Sản Phẩm Không Được Bỏ Trống");
            }  
            if (this.txtSoLuong.getText().length() == 0) {
            lblVSoLuong.setVisible(true);
            lblVSoLuong.setText("Số Lượng Không Được Bỏ Trống");
            } 
            if (this.txtGiaNhap.getText().length() == 0) {
            lblvGiaNhap.setVisible(true);
            lblvGiaNhap.setText("Giá Nhập Không Được Bỏ Trống");
            }  
            if (this.txtGiaBan.getText().length() == 0) {
            lblvGiaBan.setVisible(true);
            lblvGiaBan.setText("Giá Bán Không Được Bỏ Trống");
            }  
            if (this.txtThoiGianBH.getText().length() == 0) {
            lblvTGBH.setVisible(true);
            lblvTGBH.setText("Thời Gian Bảo Hành Không Được Bỏ Trống");
            } 
        }else {
            
            SanPham sp = new SanPham(MaSP, TenSanPham, SoLuong, DonViTinh, GiaNhap, GiaBan, NgayNhap, MaLoaiSp, HangSX, ThoiGianBH, HinhAnh, GhiChu);
            ThongBao.ThongBaoDangNhap("Thông Báo", " Được Thêm Thành Công");
            BLLSanPham.ThemSanPham(sp);
            BLLSanPham.LoadSanPham(tblDanhSach);
        }
    }//GEN-LAST:event_SbtnThemActionPerformed

    private void SbtnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnSuaActionPerformed
        if (this.txtMaSanPham.getText().length() == 0) {
            ThongBao.ThongBaoSQL(null, "Bạn Chưa Chọn Dòng Để Sửa !!");
        } else if (this.txtTenSanPham.getText().length() == 0) {
            ThongBao.ThongBaoSQL(null, "Tên Sản Phẩm Không Được Bỏ Trống");
        } else if (this.txtSoLuong.getText().length() == 0) {
            ThongBao.ThongBaoSQL(null, "Số Lượng Không Được Bỏ Trống");
        } else if (this.txtGiaNhap.getText().length() == 0) {
            ThongBao.ThongBaoSQL(null, "Giá nhập Không Được Bỏ Trống");
        } else if (this.txtGiaBan.getText().length() == 0) {
            ThongBao.ThongBaoSQL(null, "Giá Bán Không Được Bỏ Trống");
        } else if (this.txtThoiGianBH.getText().length() == 0) {
            ThongBao.ThongBaoSQL(null, "Thời gian bảo hành Không Được Bỏ Trống");
        } else {

            String MaSP = txtMaSanPham.getText();
            String TenSanPham = txtTenSanPham.getText();
            int SoLuong = Integer.valueOf(txtSoLuong.getText());
            String DonViTinh = cbbDVT.getSelectedItem().toString();
            double GiaNhap = ChuyenDoi.LaySoDouble(txtGiaNhap.getText());
            double GiaBan = ChuyenDoi.LaySoDouble(txtGiaBan.getText());
            Date NgayNhap = txtNgayNhap.getDate();
            String MaLoaiSp;
            Mycombobox myCbb = (Mycombobox) cbbLoaiSP.getSelectedItem();
            MaLoaiSp = myCbb.MaString();
            String HangSX;
            Mycombobox mycbb = (Mycombobox) cbbHangSX.getSelectedItem();
            HangSX = mycbb.MaString();
            String ThoiGianBH = txtThoiGianBH.getText();
            String HinhAnh = txtHinhAnh.getText();
            String GhiChu = txtGhiChu.getText();

            SanPham sp = new SanPham(MaSP, TenSanPham, SoLuong, DonViTinh, GiaNhap, GiaBan, NgayNhap, MaLoaiSp, HangSX, ThoiGianBH, HinhAnh, GhiChu);
            ThongBao.ThongBaoDangNhap("Thông Báo", " Đã Sửa Thành Công");
            BLLSanPham.UpdateSanPham(sp);
            BLLSanPham.LoadSanPham(tblDanhSach);
        }
    }//GEN-LAST:event_SbtnSuaActionPerformed

    private void SbtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnXoaActionPerformed
        if (this.txtMaSanPham.getText().length() == 0) {
            ThongBao.ThongBaoSQL(null, " Bạn Chưa Chọn Dòng Để Xoá !!");

        } else {
            int DSViTri[] = tblDanhSach.getSelectedRows();
            List<String> lstMaSP = new ArrayList<>();

            for (int i : DSViTri) {
                String MaNV = tblDanhSach.getValueAt(i, 1).toString();
                lstMaSP.add(MaNV);
            }

            BLLSanPham.Delete(lstMaSP);
            
             ThongBao.ThongBaoDangNhap("Thông Báo", " Xóa Thành Công");

            BLLSanPham.LoadSanPham(tblDanhSach);
        }
    }//GEN-LAST:event_SbtnXoaActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        String TenSp = "%" + txtTimKiem.getText() + "%";
        
        

        BLLSanPham.TimSanPham(tblDanhSach, TenSp);
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void txtSoLuongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoLuongKeyReleased
        // TODO add your handling code here:
        HoTroNhapSo.luonNhapSo(evt);
        lblVSoLuong.setVisible(false);
    }//GEN-LAST:event_txtSoLuongKeyReleased

    private void txtGiaNhapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiaNhapKeyReleased
        // TODO add your handling code here:
        HoTroNhapSo.luonNhapSo(evt);
        lblvGiaNhap.setVisible(false);
    }//GEN-LAST:event_txtGiaNhapKeyReleased

    private void txtGiaBanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiaBanKeyReleased
        HoTroNhapSo.luonNhapSo(evt);
        lblvGiaBan.setVisible(false);
    }//GEN-LAST:event_txtGiaBanKeyReleased

    private void txtTenSanPhamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenSanPhamKeyReleased
        lblTensp.setVisible(false);
    }//GEN-LAST:event_txtTenSanPhamKeyReleased

    private void txtThoiGianBHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtThoiGianBHKeyReleased
       lblvTGBH.setVisible(false);
    }//GEN-LAST:event_txtThoiGianBHKeyReleased

    private void SbtnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnLamMoiActionPerformed
        txtTenSanPham.setText("");
        txtGhiChu.setText("");
        txtGiaBan.setText("");
        txtGiaNhap.setText("");
        txtHinhAnh.setText("");
        txtMaSanPham.setText("");
        txtThoiGianBH.setText("");
        txtSoLuong.setText("1");
        lblTensp.setVisible(false);
        lblVSoLuong.setVisible(false);
        lblvGiaNhap.setVisible(false);
        lblvGiaBan.setVisible(false);
        lblvTGBH.setVisible(false);
    }//GEN-LAST:event_SbtnLamMoiActionPerformed

    private void txtHinhAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHinhAnhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHinhAnhActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.shady.scontrols.SButton SbtnChonHinh;
    private com.shady.scontrols.SButton SbtnLamMoi;
    private com.shady.scontrols.SButton SbtnSua;
    private com.shady.scontrols.SButton SbtnThem;
    private com.shady.scontrols.SButton SbtnXoa;
    private javax.swing.JButton btnHangSX;
    private javax.swing.JButton btnLoaiSP;
    private javax.swing.JComboBox<String> cbbDVT;
    private javax.swing.JComboBox<String> cbbHangSX;
    private javax.swing.JComboBox<String> cbbLoaiSP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblDonViTinh;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblGhiChu1;
    private javax.swing.JLabel lblGiaBan;
    private javax.swing.JLabel lblGiaNhap;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JLabel lblMHSX;
    private javax.swing.JLabel lblNgayNhap;
    private javax.swing.JLabel lblSanPham;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenSanPham;
    private javax.swing.JLabel lblTensp;
    private javax.swing.JLabel lblTensp1;
    private javax.swing.JLabel lblThoiGianBaoHanh;
    private javax.swing.JLabel lblVSoLuong;
    private javax.swing.JLabel lblVSoLuong1;
    private javax.swing.JLabel lblVSoLuong2;
    private javax.swing.JLabel lblVSoLuong3;
    private javax.swing.JLabel lblvGiaBan;
    private javax.swing.JLabel lblvGiaBan1;
    private javax.swing.JLabel lblvGiaNhap;
    private javax.swing.JLabel lblvTGBH;
    private javax.swing.JLabel llblMLSP;
    private com.shady.scontrols.STable tblDanhSach;
    private com.shady.scontrols.STextField txtGhiChu;
    private com.shady.scontrols.STextField txtGiaBan;
    private com.shady.scontrols.STextField txtGiaNhap;
    private javax.swing.JTextField txtHinhAnh;
    private com.shady.scontrols.STextField txtMaSanPham;
    private com.toedter.calendar.JDateChooser txtNgayNhap;
    private com.shady.scontrols.STextField txtSoLuong;
    private com.shady.scontrols.STextField txtTenSanPham;
    private com.shady.scontrols.STextField txtThoiGianBH;
    private com.shady.scontrols.STextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
